// GENERATED by scripts/i18n-codegen.mjs from messages/en.json — DO NOT EDIT.
// Run `pnpm run i18n:codegen` after changing en.json. CI guards this with
// `git diff --exit-code` (see .github/workflows/ci.yml).

/** Every translatable message key, derived from the English base catalog. */
export type MsgKey =
  | "about.build"
  | "about.build_hint"
  | "about.col.library"
  | "about.col.license"
  | "about.col.role"
  | "about.copied"
  | "about.copy"
  | "about.copy_build_id.title"
  | "about.date"
  | "about.date.title"
  | "about.logo_alt"
  | "about.third_party"
  | "about.third_party.intro"
  | "about.title"
  | "app.bar.open"
  | "app.bar.save"
  | "app.drop.sub"
  | "app.drop.title"
  | "app.gcode.label"
  | "app.gcode.lines"
  | "app.gcode.toggle_tip"
  | "app.loading.about"
  | "app.loading.gcode"
  | "app.loading.machine"
  | "app.loading.settings"
  | "app.loading.threed"
  | "app.loading.tools"
  | "app.panel.back"
  | "app.redo.aria"
  | "app.redo.none"
  | "app.redo.tip"
  | "app.regions.label"
  | "app.regions.tip"
  | "app.report.aria"
  | "app.report.tip"
  | "app.save.carved_stl"
  | "app.save.carved_stl_solid"
  | "app.save.carved_stl_solid.title"
  | "app.save.close_menu"
  | "app.save.gcode"
  | "app.save.gcode_back"
  | "app.save.gcode_front"
  | "app.save.options"
  | "app.save.project"
  | "app.screen.close_menu"
  | "app.screen.goto"
  | "app.screen.label"
  | "app.screen.next"
  | "app.screen.prev"
  | "app.sheet.gcode"
  | "app.sheet.operations"
  | "app.sheet.stock_layers"
  | "app.splitter.gcode_tip"
  | "app.splitter.sidebar_tip"
  | "app.status.hints_idle"
  | "app.status.hints_selection"
  | "app.status.object_many"
  | "app.status.object_one"
  | "app.status.pick_approach"
  | "app.status.ready"
  | "app.status.tab_placement"
  | "app.stock.collapse"
  | "app.stock.collapse_prev"
  | "app.stock.dims_tip"
  | "app.stock.dims_tip_current"
  | "app.stock.expand"
  | "app.stock.name"
  | "app.tab.about"
  | "app.tab.about_tip"
  | "app.tab.areas"
  | "app.tab.help"
  | "app.tab.help_tip"
  | "app.tab.machine"
  | "app.tab.machine_tip"
  | "app.tab.project"
  | "app.tab.settings"
  | "app.tab.settings_tip"
  | "app.tab.tools"
  | "app.tab.tools_tip"
  | "app.toolbar.open_tip"
  | "app.toolbar.save_tip"
  | "app.undo.aria"
  | "app.undo.none"
  | "app.undo.tip"
  | "app.viewport.mode"
  | "app.viewport.threed_tip"
  | "calib.current"
  | "calib.implausible"
  | "calib.invalid"
  | "calib.measured_width"
  | "calib.result"
  | "calib.step.cut"
  | "calib.step.enter"
  | "calib.step.measure"
  | "calib.title"
  | "canvas.add_to_selection.aria"
  | "canvas.add_to_selection.title"
  | "canvas.ctx.dismiss"
  | "canvas.ctx.empty_hint"
  | "canvas.ctx.new_op_from_selection"
  | "canvas.ctx.set_text_origin"
  | "canvas.ctx.set_text_origin.title"
  | "canvas.ctx.text_layer"
  | "canvas.firstrun.click_select"
  | "canvas.firstrun.longpress_op"
  | "canvas.firstrun.multiselect"
  | "canvas.firstrun.rightclick_op"
  | "canvas.firstrun.tap_select"
  | "canvas.fit_view.aria"
  | "canvas.fit_view.title"
  | "canvas.help.aria"
  | "canvas.help.title"
  | "canvas.selection_hud"
  | "canvas.snap_off"
  | "canvas.tab_popover.delete"
  | "canvas.tab_popover.header"
  | "canvas.tab_popover.height"
  | "canvas.tab_popover.width"
  | "common.apply"
  | "common.cancel"
  | "common.close"
  | "common.discard"
  | "common.discard_unsaved"
  | "common.done"
  | "common.keep_editing"
  | "common.load_ellipsis"
  | "common.ok"
  | "common.revert"
  | "common.save_ellipsis"
  | "dialog.action.load_recent_project"
  | "dialog.action.load_sample"
  | "dialog.action.open_another_file"
  | "dialog.action.open_another_project"
  | "dialog.action.open_dropped_drawing"
  | "dialog.action.open_dropped_project"
  | "dialog.export_stl.no_stock"
  | "dialog.loading.dxf"
  | "dialog.loading.file"
  | "dialog.loading.gcode"
  | "dialog.loading.hpgl"
  | "dialog.loading.project"
  | "dialog.loading.sample"
  | "dialog.loading.stl"
  | "dialog.loading.svg"
  | "dialog.open_drawing.add_to_layers"
  | "dialog.open_drawing.body"
  | "dialog.open_drawing.new_project"
  | "dialog.open_drawing.title"
  | "dialog.quit.confirm_body"
  | "dialog.quit.discard_quit"
  | "dialog.quit.quit"
  | "dialog.quit.save_quit"
  | "dialog.quit.title"
  | "dialog.quit.unsaved_body"
  | "dialog.text.add"
  | "dialog.text.depth"
  | "dialog.text.depth.title"
  | "dialog.text.discard_prompt"
  | "dialog.text.engraving_mismatch"
  | "dialog.text.error.empty"
  | "dialog.text.error.no_engraving_font"
  | "dialog.text.error.no_font"
  | "dialog.text.font"
  | "dialog.text.font.bundled.title"
  | "dialog.text.font.custom.title"
  | "dialog.text.font.loaded"
  | "dialog.text.font.single_line_suffix"
  | "dialog.text.no_tool"
  | "dialog.text.pos_x"
  | "dialog.text.pos_x.title"
  | "dialog.text.pos_y"
  | "dialog.text.pos_y.title"
  | "dialog.text.size"
  | "dialog.text.size.title"
  | "dialog.text.style"
  | "dialog.text.style.carve_inside"
  | "dialog.text.style.carve_inside.help"
  | "dialog.text.style.engraving"
  | "dialog.text.style.engraving.help"
  | "dialog.text.style.outline_inside"
  | "dialog.text.style.outline_inside.help"
  | "dialog.text.style.outline_outside"
  | "dialog.text.style.outline_outside.help"
  | "dialog.text.style.plain"
  | "dialog.text.style.plain.help"
  | "dialog.text.style.pocket_inside"
  | "dialog.text.style.pocket_inside.help"
  | "dialog.text.style.pocket_outside"
  | "dialog.text.style.pocket_outside.help"
  | "dialog.text.switch_font"
  | "dialog.text.text"
  | "dialog.text.text.title"
  | "dialog.text.title"
  | "dialog.text.tool"
  | "dialog.text.tool.title"
  | "dialog.text.width"
  | "dialog.text.width.title"
  | "dialog.unsaved.body"
  | "dialog.unsaved.dont_save"
  | "dialog.unsaved.save_continue"
  | "dialog.unsaved.title"
  | "error.code.cps_post_failed"
  | "error.code.cps_selection_missing"
  | "error.code.cps_unavailable"
  | "error.code.internal_panic"
  | "error.code.missing_tool"
  | "error.code.text_render_failed"
  | "error.code.two_sided_through"
  | "error.code.unimplemented_op_kind"
  | "error.code.unknown_post_processor"
  | "error.fix.apply"
  | "error.fix.assign_tool"
  | "error.fix.change_profile_offset"
  | "error.fix.disable_op"
  | "error.fix.lower_sim_resolution"
  | "error.hint.cps_post_failed"
  | "error.hint.cps_selection_missing"
  | "error.hint.cps_unavailable"
  | "error.hint.internal_panic"
  | "error.hint.missing_tool"
  | "error.hint.text_render_failed"
  | "error.hint.two_sided_through"
  | "error.hint.unimplemented_op_kind"
  | "error.hint.unknown_post_processor"
  | "error.span"
  | "gcode.label"
  | "gcode.line_sync_unavailable"
  | "gcode.line_sync_unavailable.title"
  | "gcode.silenced"
  | "gcode.silenced.title"
  | "gcode.stale"
  | "gcode.stale.title"
  | "gcode.tab.back"
  | "gcode.tab.front"
  | "gcode.tab.readonly"
  | "gcode.tab.readonly.title"
  | "gcode.tab.title"
  | "genbar.chip.clean"
  | "genbar.chip.critical"
  | "genbar.chip.details_title"
  | "genbar.chip.idle"
  | "genbar.chip.stale"
  | "genbar.chip.warnings"
  | "genbar.download.back"
  | "genbar.download.front"
  | "genbar.download.ngc"
  | "genbar.download.plt"
  | "genbar.download.stl_title"
  | "genbar.download.title"
  | "genbar.error.block_critical"
  | "genbar.error.block_work_area"
  | "genbar.error.cps_post_missing"
  | "genbar.error.no_operations"
  | "genbar.generate.generate"
  | "genbar.generate.generating"
  | "genbar.generate.regenerate"
  | "genbar.generate.title"
  | "genbar.generate.title_stale"
  | "genbar.panel.aria"
  | "genbar.panel.empty"
  | "genbar.panel.title"
  | "genbar.row.apply_fix"
  | "genbar.row.apply_fix_aria"
  | "genbar.row.apply_fix_title"
  | "genbar.row.goto"
  | "genbar.row.goto_aria"
  | "genbar.row.goto_title"
  | "genbar.row.pipeline"
  | "genbar.row.pipeline_title"
  | "genbar.row.sim"
  | "genbar.row.sim_title"
  | "genbar.sim_idle_hint"
  | "genbar.source_stale.changed"
  | "genbar.source_stale.reload"
  | "genbar.source_stale.title"
  | "genbar.stats.cached"
  | "genbar.stats.summary"
  | "genbar.time.arc"
  | "genbar.time.aria"
  | "genbar.time.cut"
  | "genbar.time.plunge"
  | "genbar.time.rapid"
  | "genbar.time.retract"
  | "genbar.time.spindle_warmup"
  | "genbar.time.toolchange"
  | "genbar.time.total"
  | "layers.add"
  | "layers.add.open_file"
  | "layers.add.open_file.title"
  | "layers.add.text"
  | "layers.add.text.title"
  | "layers.add.title"
  | "layers.caret.collapse.aria"
  | "layers.caret.collapse.title"
  | "layers.caret.expand.aria"
  | "layers.caret.expand.title"
  | "layers.drawings"
  | "layers.empty.open_file"
  | "layers.empty.sub"
  | "layers.empty.title"
  | "layers.file_stats"
  | "layers.file_stats.title"
  | "layers.import_remove.aria"
  | "layers.import_remove.title"
  | "layers.import_stats"
  | "layers.reopen.accept"
  | "layers.reopen.dismiss"
  | "layers.reopen.prefix"
  | "layers.reopen.suffix"
  | "layers.row.delete.aria"
  | "layers.row.delete.title"
  | "layers.row.toggle.title"
  | "layers.title"
  | "layers.toggle_all.aria"
  | "layers.toggle_all.title"
  | "layers.xform.active.aria"
  | "layers.xform.head.title"
  | "layers.xform.label"
  | "layers.xform.mirror_x"
  | "layers.xform.mirror_x.title"
  | "layers.xform.mirror_y"
  | "layers.xform.mirror_y.title"
  | "layers.xform.reset"
  | "layers.xform.reset.title"
  | "layers.xform.rotate"
  | "layers.xform.rotate.title"
  | "layers.xform.scale"
  | "layers.xform.scale.title"
  | "layers.xform.tx.title"
  | "layers.xform.ty.title"
  | "machine.accel.x.aria"
  | "machine.accel.y.aria"
  | "machine.accel.z.aria"
  | "machine.accel_label"
  | "machine.arc_tol"
  | "machine.arc_tol.title"
  | "machine.cap.drag"
  | "machine.cap.laser"
  | "machine.cap.mill"
  | "machine.cap.plasma"
  | "machine.capabilities"
  | "machine.capabilities.legend_title"
  | "machine.capabilities.primary_title"
  | "machine.cps.open_file"
  | "machine.cps.post"
  | "machine.cps.post.none"
  | "machine.cps.post.title"
  | "machine.cps.properties"
  | "machine.cps.unsupported"
  | "machine.decimal_sep"
  | "machine.decimal_sep.comma"
  | "machine.decimal_sep.period"
  | "machine.decimal_sep.title"
  | "machine.dialect"
  | "machine.dialect.cps"
  | "machine.dialect.title"
  | "machine.emit_arcs"
  | "machine.emit_arcs.title"
  | "machine.emit_comments"
  | "machine.emit_comments.title"
  | "machine.fast_move_z"
  | "machine.fast_move_z.title"
  | "machine.hpgl_note"
  | "machine.jerk.x.aria"
  | "machine.jerk.y.aria"
  | "machine.jerk.z.aria"
  | "machine.jerk_enable"
  | "machine.jerk_enable.title"
  | "machine.jerk_label"
  | "machine.laser_dynamic"
  | "machine.laser_dynamic.title"
  | "machine.line_num"
  | "machine.line_num.placeholder"
  | "machine.line_num.title"
  | "machine.load.title"
  | "machine.max_feed"
  | "machine.max_feed.title"
  | "machine.mode"
  | "machine.mode.drag"
  | "machine.mode.laser"
  | "machine.mode.mill"
  | "machine.mode.plasma"
  | "machine.mode.title"
  | "machine.name"
  | "machine.name.input_title"
  | "machine.name.label_title"
  | "machine.optional_stop"
  | "machine.optional_stop.title"
  | "machine.park.x.aria"
  | "machine.park.y.aria"
  | "machine.park_home"
  | "machine.park_home.title"
  | "machine.park_xy.help"
  | "machine.park_xy_label"
  | "machine.plot_mode"
  | "machine.plot_mode.title"
  | "machine.pp.edit_btn"
  | "machine.pp.no_overrides"
  | "machine.pp.overrides"
  | "machine.pp.tweak.axes"
  | "machine.pp.tweak.coolant"
  | "machine.pp.tweak.file"
  | "machine.pp.tweak.footer"
  | "machine.pp.tweak.header"
  | "machine.pp.tweak.mist"
  | "machine.pp.tweak.toolchange"
  | "machine.profile.delete"
  | "machine.profile.delete.title"
  | "machine.profile.delete_confirm"
  | "machine.profile.dirty_switch.title"
  | "machine.profile.duplicate"
  | "machine.profile.duplicate.title"
  | "machine.profile.label"
  | "machine.profile.missing_note"
  | "machine.profile.missing_note.title"
  | "machine.profile.none_option"
  | "machine.profile.pick.title"
  | "machine.profile.referenced_missing_option"
  | "machine.profile.save_as"
  | "machine.profile.save_as.title"
  | "machine.profile_preset"
  | "machine.profile_preset.custom"
  | "machine.profile_preset.grbl"
  | "machine.profile_preset.linuxcnc"
  | "machine.profile_preset.mach3"
  | "machine.profile_preset.none"
  | "machine.profile_preset.title"
  | "machine.rapid"
  | "machine.rapid.title"
  | "machine.save.title"
  | "machine.section.gcode_formatting"
  | "machine.section.kinematics"
  | "machine.section.post_profile"
  | "machine.section.spindle"
  | "machine.spindle_max"
  | "machine.spindle_max.title"
  | "machine.spindle_min"
  | "machine.spindle_min.title"
  | "machine.spindle_start_dwell"
  | "machine.spindle_start_dwell.title"
  | "machine.spindle_stop_dwell"
  | "machine.spindle_stop_dwell.title"
  | "machine.storage_note"
  | "machine.title"
  | "machine.toolchange"
  | "machine.toolchange.atc"
  | "machine.toolchange.ignore"
  | "machine.toolchange.m0_pause"
  | "machine.toolchange.m6_prompt"
  | "machine.toolchange.title"
  | "machine.toolchange_time"
  | "machine.toolchange_time.title"
  | "machine.unit"
  | "machine.unit.inch"
  | "machine.unit.mm"
  | "machine.unit.title"
  | "machine.work_area"
  | "machine.work_area.legend_title"
  | "machinetool.add"
  | "machinetool.add.title"
  | "machinetool.already_stocked.title"
  | "machinetool.filter.placeholder"
  | "machinetool.filter.title"
  | "machinetool.incompatible"
  | "machinetool.incompatible.title"
  | "machinetool.incompatible_tool.title"
  | "machinetool.inventory_empty"
  | "machinetool.remove"
  | "machinetool.remove.title"
  | "machinetool.remove_last.title"
  | "machinetool.remove_used.title.one"
  | "machinetool.remove_used.title.other"
  | "machinetool.shop_inventory"
  | "machinetool.shop_inventory.title"
  | "machinetool.stocked"
  | "machinetool.stocked_col"
  | "machinetool.stocked_col.title"
  | "machinews.delete"
  | "machinews.delete.confirm"
  | "machinews.delete.title"
  | "machinews.duplicate"
  | "machinews.duplicate.title"
  | "machinews.load_file"
  | "machinews.load_file.title"
  | "machinews.machine"
  | "machinews.missing"
  | "machinews.missing.title"
  | "machinews.new"
  | "machinews.new.title"
  | "machinews.pick.title"
  | "machinews.project_local"
  | "machinews.referenced_missing"
  | "machinews.save_file"
  | "machinews.save_file.title"
  | "machinews.sections.aria"
  | "machinews.settings"
  | "machinews.settings.title"
  | "machinews.tooling"
  | "machinews.tooling.title"
  | "menu.aria.more_actions"
  | "menu.aria.trigger"
  | "menu.exit"
  | "menu.no_recent"
  | "menu.open"
  | "menu.recent_projects"
  | "menu.redo"
  | "menu.report"
  | "menu.save_gcode"
  | "menu.save_gcode_back"
  | "menu.save_gcode_front"
  | "menu.save_project"
  | "menu.save_stl"
  | "menu.show_regions"
  | "menu.undo"
  | "modeswitch.add_default"
  | "modeswitch.affected.many"
  | "modeswitch.affected.one"
  | "modeswitch.assign.all"
  | "modeswitch.assign.one"
  | "modeswitch.dismiss.aria"
  | "modeswitch.dismiss.title"
  | "modeswitch.none"
  | "oplist.activate.aria"
  | "oplist.add.aria"
  | "oplist.add.title"
  | "oplist.collapse.aria"
  | "oplist.collapse.title"
  | "oplist.count.title"
  | "oplist.delete.aria"
  | "oplist.delete.title"
  | "oplist.duplicate.aria"
  | "oplist.duplicate.title"
  | "oplist.empty.cta"
  | "oplist.empty.sub"
  | "oplist.empty.title"
  | "oplist.expand.title"
  | "oplist.filter.all"
  | "oplist.filter.empty"
  | "oplist.filter.title"
  | "oplist.grip.title"
  | "oplist.group_by_tool"
  | "oplist.group_by_tool.title"
  | "oplist.repick"
  | "oplist.repick.aria"
  | "oplist.repick.layers_suffix"
  | "oplist.repick.title_empty"
  | "oplist.repick.title_ready"
  | "oplist.side.back"
  | "oplist.side.count.title"
  | "oplist.side.front"
  | "oplist.status.cycle_marker"
  | "oplist.status.dirty"
  | "oplist.status.gcode_include"
  | "oplist.status.homing"
  | "oplist.status.no_drawing"
  | "oplist.status.not_generated"
  | "oplist.status.orphan_layers"
  | "oplist.status.orphan_objects"
  | "oplist.status.pause"
  | "oplist.status.probe"
  | "oplist.status.tool_missing"
  | "oplist.status.up_to_date"
  | "oplist.status_btn.aria"
  | "oplist.status_btn.title"
  | "oplist.title"
  | "oplist.tool_missing"
  | "opprops.combine"
  | "opprops.combine.auto"
  | "opprops.combine.auto.help"
  | "opprops.combine.difference"
  | "opprops.combine.difference.help"
  | "opprops.combine.intersection"
  | "opprops.combine.intersection.help"
  | "opprops.combine.none"
  | "opprops.combine.none.help"
  | "opprops.combine.union"
  | "opprops.combine.union.help"
  | "opprops.combine.xor"
  | "opprops.combine.xor.help"
  | "opprops.cut"
  | "opprops.cut.approach_point"
  | "opprops.cut.approach_point.clear"
  | "opprops.cut.approach_point.clear.title"
  | "opprops.cut.approach_point.pick"
  | "opprops.cut.approach_point.pick.title"
  | "opprops.cut.approach_point.picking"
  | "opprops.cut.approach_point.picking.title"
  | "opprops.cut.approach_point.title"
  | "opprops.cut.approach_point.x_aria"
  | "opprops.cut.approach_point.y_aria"
  | "opprops.cut.depth_list"
  | "opprops.cut.depth_list.placeholder"
  | "opprops.cut.depth_list.title"
  | "opprops.cut.direction"
  | "opprops.cut.final_depth"
  | "opprops.cut.finish_direction"
  | "opprops.cut.finish_step"
  | "opprops.cut.finish_step.placeholder"
  | "opprops.cut.finish_step.title"
  | "opprops.cut.plunge"
  | "opprops.cut.start_depth"
  | "opprops.cut.step"
  | "opprops.cut.step.from_tool"
  | "opprops.cut.step.required"
  | "opprops.cut.step.reset"
  | "opprops.cut.step.reset.title"
  | "opprops.cut.through_depth"
  | "opprops.cut.through_depth.title"
  | "opprops.cut.xy_finish_stock"
  | "opprops.cut.xy_finish_stock.title"
  | "opprops.direction.climb"
  | "opprops.direction.climb.help"
  | "opprops.direction.conventional"
  | "opprops.direction.conventional.help"
  | "opprops.empty"
  | "opprops.feeds"
  | "opprops.feeds.corner_slow"
  | "opprops.feeds.corner_slow.title"
  | "opprops.feeds.custom"
  | "opprops.feeds.feed_rate"
  | "opprops.feeds.feed_rate.reset.title"
  | "opprops.feeds.feed_rate.title"
  | "opprops.feeds.fraction"
  | "opprops.feeds.fraction.title"
  | "opprops.feeds.plunge_rate"
  | "opprops.feeds.plunge_rate.reset.title"
  | "opprops.feeds.plunge_rate.title"
  | "opprops.feeds.reset"
  | "opprops.feeds.tool_default"
  | "opprops.feeds.tool_defaults"
  | "opprops.finish_tool"
  | "opprops.finish_tool.same_as_rough"
  | "opprops.finish_tool.title.drill"
  | "opprops.finish_tool.title.pocket"
  | "opprops.from_selection"
  | "opprops.from_selection.count"
  | "opprops.from_selection.disabled_aria"
  | "opprops.from_selection.title"
  | "opprops.group"
  | "opprops.group.label"
  | "opprops.group.label.placeholder"
  | "opprops.group.label.title"
  | "opprops.group.none"
  | "opprops.group.pin_order"
  | "opprops.group.pin_order.title"
  | "opprops.helix"
  | "opprops.helix_angle"
  | "opprops.helix_angle.title"
  | "opprops.helix_autofit"
  | "opprops.helix_autofit.title"
  | "opprops.helix_radius"
  | "opprops.helix_radius.auto.title"
  | "opprops.helix_radius.auto_detected"
  | "opprops.helix_radius.auto_no_fit"
  | "opprops.helix_radius.auto_no_fit_reason"
  | "opprops.helix_radius.auto_pending"
  | "opprops.helix_radius.manual.title"
  | "opprops.name"
  | "opprops.pattern"
  | "opprops.pattern.grid"
  | "opprops.pattern.linear"
  | "opprops.pattern.polar"
  | "opprops.pattern.single"
  | "opprops.plunge.direct"
  | "opprops.plunge.direct.help"
  | "opprops.plunge.helix"
  | "opprops.plunge.helix.help"
  | "opprops.plunge.ramp"
  | "opprops.plunge.ramp.help"
  | "opprops.ramp_angle"
  | "opprops.ramp_angle.title"
  | "opprops.side"
  | "opprops.side.back"
  | "opprops.side.front"
  | "opprops.side.title"
  | "opprops.source"
  | "opprops.source.all_chains"
  | "opprops.source.layer"
  | "opprops.source.layer.pick"
  | "opprops.source.mode"
  | "opprops.source.mode.all"
  | "opprops.source.mode.layer"
  | "opprops.source.mode.objects"
  | "opprops.source.objects_selected"
  | "opprops.source.text_group"
  | "opprops.tabs"
  | "opprops.tabs.auto"
  | "opprops.tabs.auto_manual"
  | "opprops.tabs.manual"
  | "opprops.tabs.off"
  | "opprops.title"
  | "opprops.tool"
  | "opprops.tool.edit"
  | "opprops.tool.incompatible_group"
  | "opprops.tool.mismatch"
  | "opprops.tool.mismatch.title"
  | "opprops.tool.title.default"
  | "opprops.tool.title.raster"
  | "opprops.tool.title.relief"
  | "opprops.wear.effective_diameter"
  | "opprops.wear.title"
  | "ops.chamfer.finish_pass.help"
  | "ops.chamfer.finish_pass.label"
  | "ops.chamfer.legend"
  | "ops.chamfer.width.help"
  | "ops.chamfer.width.label"
  | "ops.cycle_marker.emits.hint"
  | "ops.cycle_marker.label.help"
  | "ops.cycle_marker.label.label"
  | "ops.cycle_marker.label.placeholder"
  | "ops.cycle_marker.name.label"
  | "ops.cycle_marker.no_motion.hint"
  | "ops.drill.chamfer_width.help"
  | "ops.drill.chamfer_width.label"
  | "ops.drill.cycle.chip_break"
  | "ops.drill.cycle.chip_break.help"
  | "ops.drill.cycle.label"
  | "ops.drill.cycle.peck"
  | "ops.drill.cycle.peck.help"
  | "ops.drill.cycle.simple"
  | "ops.drill.cycle.simple.help"
  | "ops.drill.cycle_options"
  | "ops.drill.dwell.label"
  | "ops.drill.legend"
  | "ops.drill.peck_step.label"
  | "ops.drill.spot_depth.help"
  | "ops.drill.spot_depth.label"
  | "ops.drill.spot_first.help"
  | "ops.drill.spot_first.label"
  | "ops.drill.spot_options"
  | "ops.drill.spot_tool.label"
  | "ops.gcode_include.content.help"
  | "ops.gcode_include.content.label"
  | "ops.gcode_include.content.placeholder"
  | "ops.gcode_include.file.help"
  | "ops.gcode_include.file.label"
  | "ops.gcode_include.loaded_from.hint"
  | "ops.gcode_include.loaded_stats.hint"
  | "ops.gcode_include.name.label"
  | "ops.gcode_include.token_feed.hint"
  | "ops.gcode_include.token_safez.hint"
  | "ops.gcode_include.token_spindle.hint"
  | "ops.gcode_include.token_xyz.hint"
  | "ops.gcode_include.tokens_intro.hint"
  | "ops.gcode_include.tokens_outro.hint"
  | "ops.gcode_include.verbose_unsim_warnings.help"
  | "ops.gcode_include.verbose_unsim_warnings.label"
  | "ops.help.chamfer"
  | "ops.help.cycle_marker"
  | "ops.help.dovetail"
  | "ops.help.drag_knife"
  | "ops.help.drill"
  | "ops.help.engrave"
  | "ops.help.gcode_include"
  | "ops.help.homing"
  | "ops.help.pause"
  | "ops.help.pocket"
  | "ops.help.pocket_outside"
  | "ops.help.probe"
  | "ops.help.profile"
  | "ops.help.raster_engrave"
  | "ops.help.relief_mill"
  | "ops.help.t_slot"
  | "ops.help.thread"
  | "ops.help.vcarve"
  | "ops.help.waterline_rough"
  | "ops.homing.name.label"
  | "ops.homing.pipeline.hint_prefix"
  | "ops.homing.pipeline.hint_suffix"
  | "ops.homing.pipeline.safe_z_suffix"
  | "ops.homing.retract_safe_z.help"
  | "ops.homing.retract_safe_z.label"
  | "ops.image.none_loaded"
  | "ops.kind.chamfer"
  | "ops.kind.cycle_marker"
  | "ops.kind.dovetail"
  | "ops.kind.drag_knife"
  | "ops.kind.drill"
  | "ops.kind.engrave"
  | "ops.kind.gcode_include"
  | "ops.kind.homing"
  | "ops.kind.pause"
  | "ops.kind.pocket"
  | "ops.kind.pocket_outside"
  | "ops.kind.probe"
  | "ops.kind.profile"
  | "ops.kind.raster_engrave"
  | "ops.kind.relief_mill"
  | "ops.kind.t_slot"
  | "ops.kind.thread"
  | "ops.kind.vcarve"
  | "ops.kind.waterline_rough"
  | "ops.pattern.center_x.help"
  | "ops.pattern.center_x.label"
  | "ops.pattern.center_y.help"
  | "ops.pattern.center_y.label"
  | "ops.pattern.count_x.help"
  | "ops.pattern.count_x.label"
  | "ops.pattern.count_y.help"
  | "ops.pattern.count_y.label"
  | "ops.pattern.grid_dx.help"
  | "ops.pattern.grid_dy.help"
  | "ops.pattern.intro.hint"
  | "ops.pattern.kind.grid"
  | "ops.pattern.kind.help"
  | "ops.pattern.kind.label"
  | "ops.pattern.kind.linear"
  | "ops.pattern.kind.none"
  | "ops.pattern.kind.polar"
  | "ops.pattern.legend"
  | "ops.pattern.linear_count.help"
  | "ops.pattern.linear_count.label"
  | "ops.pattern.linear_dx.help"
  | "ops.pattern.linear_dy.help"
  | "ops.pattern.polar_count.help"
  | "ops.pattern.polar_count.label"
  | "ops.pattern.set_center"
  | "ops.pattern.set_center.disabled_help"
  | "ops.pattern.set_center.help"
  | "ops.pattern.start.help"
  | "ops.pattern.start.label"
  | "ops.pattern.step.help"
  | "ops.pattern.step.label"
  | "ops.pause.emits.hint"
  | "ops.pause.emits_and.hint"
  | "ops.pause.emits_message.hint"
  | "ops.pause.emits_slot.hint"
  | "ops.pause.message.help"
  | "ops.pause.message.label"
  | "ops.pause.message.placeholder"
  | "ops.pause.name.label"
  | "ops.picker.add_aria"
  | "ops.picker.select_first"
  | "ops.pocket.engagement_angle.help"
  | "ops.pocket.engagement_angle.label"
  | "ops.pocket.frame.legend"
  | "ops.pocket.frame.shape.rectangle"
  | "ops.pocket.frame.shape.rounded_rectangle"
  | "ops.pocket.frame.summary"
  | "ops.pocket.frame_corner_radius.help"
  | "ops.pocket.frame_corner_radius.label"
  | "ops.pocket.frame_corner_radius.placeholder"
  | "ops.pocket.frame_padding.help"
  | "ops.pocket.frame_padding.label"
  | "ops.pocket.frame_shape.help"
  | "ops.pocket.frame_shape.label"
  | "ops.pocket.halfpipe.profile.circular_arc"
  | "ops.pocket.halfpipe.profile.v_bottom"
  | "ops.pocket.halfpipe.summary"
  | "ops.pocket.halfpipe_profile.help"
  | "ops.pocket.halfpipe_profile.hint"
  | "ops.pocket.included_angle.help"
  | "ops.pocket.included_angle.label"
  | "ops.pocket.legend"
  | "ops.pocket.loop_radius_factor.help"
  | "ops.pocket.loop_radius_factor.label"
  | "ops.pocket.outside.convert"
  | "ops.pocket.outside.help"
  | "ops.pocket.outside.hint"
  | "ops.pocket.outside.legend"
  | "ops.pocket.profile.help"
  | "ops.pocket.profile.label"
  | "ops.pocket.radius.help"
  | "ops.pocket.radius.label"
  | "ops.pocket.strategy.cascade"
  | "ops.pocket.strategy.halfpipe"
  | "ops.pocket.strategy.label"
  | "ops.pocket.strategy.spiral"
  | "ops.pocket.strategy.trochoidal"
  | "ops.pocket.strategy.zigzag"
  | "ops.pocket.trochoidal.summary"
  | "ops.pocket.trochoidal_climb.hint"
  | "ops.pocket.trochoidal_plunge.hint"
  | "ops.pocket.trochoidal_tabs.hint"
  | "ops.pocket.xy_overlap.help_empty"
  | "ops.pocket.xy_overlap.help_set"
  | "ops.pocket.xy_overlap.inherit_global"
  | "ops.pocket.xy_overlap.inherit_tool"
  | "ops.pocket.xy_overlap.label"
  | "ops.pocket.xy_overlap.source_global"
  | "ops.pocket.xy_overlap.source_tool"
  | "ops.pocket.xy_overlap.unit_help"
  | "ops.pocket.zigzag.summary"
  | "ops.pocket.zigzag_angle.help"
  | "ops.pocket.zigzag_angle.label"
  | "ops.pocket.zigzag_angle_quick.help"
  | "ops.probe.axis.help"
  | "ops.probe.axis.label"
  | "ops.probe.distance.help"
  | "ops.probe.distance.label"
  | "ops.probe.emits.hint"
  | "ops.probe.feed.help"
  | "ops.probe.feed.label"
  | "ops.probe.halts.hint"
  | "ops.probe.name.label"
  | "ops.profile.lead.off"
  | "ops.profile.lead.straight"
  | "ops.profile.lead_in.arc"
  | "ops.profile.lead_in.help"
  | "ops.profile.lead_in.label"
  | "ops.profile.lead_in_length.help"
  | "ops.profile.lead_in_radius.help"
  | "ops.profile.lead_out.arc"
  | "ops.profile.lead_out.help"
  | "ops.profile.lead_out.label"
  | "ops.profile.lead_out_length.help"
  | "ops.profile.lead_out_radius.help"
  | "ops.profile.leads.legend"
  | "ops.profile.legend"
  | "ops.profile.length.label"
  | "ops.profile.offset.label"
  | "ops.profile.radius.label"
  | "ops.profile.side.inside"
  | "ops.profile.side.on"
  | "ops.profile.side.outside"
  | "ops.raster.power_curve.legend"
  | "ops.raster.scan.along_x"
  | "ops.raster.scan.along_y"
  | "ops.raster.scan.bidirectional"
  | "ops.raster.scan.legend"
  | "ops.raster.scan.lift_between"
  | "ops.raster.source.legend"
  | "ops.raster_engrave.decoding"
  | "ops.raster_engrave.dimensions.hint"
  | "ops.raster_engrave.direction.label"
  | "ops.raster_engrave.estimate.label"
  | "ops.raster_engrave.estimate_rough"
  | "ops.raster_engrave.histogram.hint"
  | "ops.raster_engrave.histogram_level.hint"
  | "ops.raster_engrave.image.label"
  | "ops.raster_engrave.intro.hint"
  | "ops.raster_engrave.level.help"
  | "ops.raster_engrave.level.label"
  | "ops.raster_engrave.link.help"
  | "ops.raster_engrave.link.label"
  | "ops.raster_engrave.load_error.hint"
  | "ops.raster_engrave.load_image"
  | "ops.raster_engrave.matrix.help"
  | "ops.raster_engrave.matrix.label"
  | "ops.raster_engrave.max_s.help"
  | "ops.raster_engrave.max_s.label"
  | "ops.raster_engrave.min_s.help"
  | "ops.raster_engrave.min_s.label"
  | "ops.raster_engrave.overscan.help"
  | "ops.raster_engrave.overscan.label"
  | "ops.raster_engrave.power_curve.bayer"
  | "ops.raster_engrave.power_curve.floyd_steinberg"
  | "ops.raster_engrave.power_curve.label"
  | "ops.raster_engrave.power_curve.linear"
  | "ops.raster_engrave.power_curve.threshold"
  | "ops.raster_engrave.power_s.help"
  | "ops.raster_engrave.power_s.label"
  | "ops.raster_engrave.preview.help"
  | "ops.raster_engrave.resolution.help"
  | "ops.raster_engrave.resolution.label"
  | "ops.raster_engrave.width.help"
  | "ops.raster_engrave.width.label"
  | "ops.relief.depth.legend"
  | "ops.relief.finish.legend"
  | "ops.relief.scan.along_x"
  | "ops.relief.scan.along_y"
  | "ops.relief.source.legend"
  | "ops.relief_mill.decoding"
  | "ops.relief_mill.depth_limit.help"
  | "ops.relief_mill.depth_limit.hint"
  | "ops.relief_mill.depth_limit.label"
  | "ops.relief_mill.depth_limit.placeholder"
  | "ops.relief_mill.dimensions.hint"
  | "ops.relief_mill.image.label"
  | "ops.relief_mill.invert.help"
  | "ops.relief_mill.invert.label"
  | "ops.relief_mill.load_error.hint"
  | "ops.relief_mill.load_image"
  | "ops.relief_mill.load_stl"
  | "ops.relief_mill.scallop.help"
  | "ops.relief_mill.scallop.label"
  | "ops.relief_mill.scan.label"
  | "ops.relief_mill.step.help"
  | "ops.relief_mill.step.label"
  | "ops.relief_mill.stepover.help"
  | "ops.relief_mill.stepover.label"
  | "ops.relief_mill.stepover.placeholder"
  | "ops.relief_mill.stl.dimensions.hint"
  | "ops.relief_mill.stl.no_footprint"
  | "ops.relief_mill.surfacing.hint"
  | "ops.relief_mill.width.help"
  | "ops.relief_mill.width.label"
  | "ops.relief_mill.width.stl_locked"
  | "ops.relief_mill.z_max.help"
  | "ops.relief_mill.z_max.label"
  | "ops.relief_mill.z_min.help"
  | "ops.relief_mill.z_min.label"
  | "ops.tabs.clear"
  | "ops.tabs.count.help"
  | "ops.tabs.count.label"
  | "ops.tabs.disconnected.help"
  | "ops.tabs.disconnected.hint"
  | "ops.tabs.height.help"
  | "ops.tabs.height.label"
  | "ops.tabs.legend"
  | "ops.tabs.manual.help"
  | "ops.tabs.manual.hint"
  | "ops.tabs.manual.placed"
  | "ops.tabs.mode.help"
  | "ops.tabs.mode.label"
  | "ops.tabs.ramp.summary"
  | "ops.tabs.ramp_angle.help"
  | "ops.tabs.ramp_angle.label"
  | "ops.tabs.type.label"
  | "ops.tabs.type.ramp"
  | "ops.tabs.type.ramp.help"
  | "ops.tabs.type.rectangle"
  | "ops.tabs.type.rectangle.help"
  | "ops.tabs.width.help"
  | "ops.tabs.width.label"
  | "ops.thread.climb.help"
  | "ops.thread.climb.label"
  | "ops.thread.direction.help"
  | "ops.thread.direction.label"
  | "ops.thread.legend"
  | "ops.thread.pitch.help"
  | "ops.thread.pitch.label"
  | "ops.thread.side.external"
  | "ops.thread.side.internal"
  | "ops.thread.source.help"
  | "ops.thread.source.hint"
  | "ops.vcarve.advanced.summary"
  | "ops.vcarve.duplicate_as_inlay_plug"
  | "ops.vcarve.inlay_plug.help"
  | "ops.vcarve.inlay_plug.label"
  | "ops.vcarve.legend"
  | "ops.vcarve.max_width.help"
  | "ops.vcarve.max_width.label"
  | "ops.vcarve.max_width.placeholder"
  | "ops.vcarve.mode.help"
  | "ops.vcarve.mode.label"
  | "ops.vcarve.mode.medial_axis"
  | "ops.vcarve.mode.perimeter"
  | "ops.vcarve.refine_pass.help"
  | "ops.vcarve.refine_pass.label"
  | "ops.vcarve.refine_pass.not_implemented"
  | "ops.vcarve.source_inset.help"
  | "ops.vcarve.source_inset.label"
  | "ops.waterline.floor.help"
  | "ops.waterline.floor.label"
  | "ops.waterline.floor.placeholder"
  | "ops.waterline.levels.legend"
  | "ops.waterline.load_stl"
  | "ops.waterline.needs_stl.hint"
  | "ops.waterline.roughing.hint"
  | "ops.waterline.stepover.help"
  | "ops.waterline.stepover.label"
  | "ops.waterline.z_step.help"
  | "ops.waterline.z_step.label"
  | "panel.drag_to_move"
  | "panel.drag_to_resize"
  | "panel.header.aria"
  | "panel.header.aria_draggable"
  | "phonewarn.chip.generate"
  | "phonewarn.chip.ok"
  | "phonewarn.chip.stale"
  | "phonewarn.copied"
  | "phonewarn.copy"
  | "phonewarn.empty"
  | "phonewarn.fix_wcs"
  | "phonewarn.panel.aria"
  | "phonewarn.panel.title"
  | "phonewarn.title.generating"
  | "phonewarn.title.many"
  | "phonewarn.title.no_program"
  | "phonewarn.title.no_warnings"
  | "phonewarn.title.one"
  | "phonewarn.title.stale"
  | "playback.next_op"
  | "playback.next_op.named"
  | "playback.pause"
  | "playback.play"
  | "playback.position"
  | "playback.prev_op"
  | "playback.prev_op.named"
  | "playback.scrub.exact"
  | "playback.scrub.forward"
  | "playback.speed"
  | "playback.speed.aria"
  | "playback.tick.jump"
  | "playback.tick.silenced"
  | "playback.valuetext"
  | "playback.valuetext.named"
  | "post.axes.axis"
  | "post.axes.disabled"
  | "post.axes.enable_aria"
  | "post.axes.feed"
  | "post.axes.format"
  | "post.axes.format_aria"
  | "post.axes.i_arc"
  | "post.axes.j_arc"
  | "post.axes.name"
  | "post.axes.name_aria"
  | "post.axes.on"
  | "post.axes.scale"
  | "post.axes.scale.title"
  | "post.axes.scale_aria"
  | "post.axes.spindle"
  | "post.coolant_flood_off"
  | "post.coolant_flood_on"
  | "post.coolant_mist_on"
  | "post.discard_prompt"
  | "post.export_json"
  | "post.extension"
  | "post.file_output"
  | "post.import_err.axes_incomplete"
  | "post.import_err.parse"
  | "post.import_json"
  | "post.keep_editing"
  | "post.line_ending"
  | "post.line_ending.crlf"
  | "post.line_ending.lf"
  | "post.per_axis"
  | "post.per_axis.hint_after"
  | "post.per_axis.hint_before"
  | "post.per_axis.hint_mid"
  | "post.per_axis.override"
  | "post.preview"
  | "post.preview.sub"
  | "post.profile_name"
  | "post.profile_name.placeholder"
  | "post.program_end"
  | "post.program_start"
  | "post.save"
  | "post.templates"
  | "post.templates.case_insensitive"
  | "post.templates.marker.diameter"
  | "post.templates.marker.feed"
  | "post.templates.marker.newline"
  | "post.templates.marker.spindle"
  | "post.templates.marker.tool_name"
  | "post.templates.marker.tool_num"
  | "post.templates.markers"
  | "post.title"
  | "post.tokens.d"
  | "post.tokens.f"
  | "post.tokens.intro_after"
  | "post.tokens.intro_before"
  | "post.tokens.n"
  | "post.tokens.nl"
  | "post.tokens.op"
  | "post.tokens.project"
  | "post.tokens.s"
  | "post.tokens.summary"
  | "post.tokens.t"
  | "post.tokens.tools"
  | "post.tokens.version"
  | "post.tool_change"
  | "recent.button"
  | "recent.clear"
  | "recent.open_hint"
  | "report.brand_subtitle"
  | "report.generated_by"
  | "report.ops.col.depth"
  | "report.ops.col.kind"
  | "report.ops.col.name"
  | "report.ops.col.source"
  | "report.ops.col.status"
  | "report.ops.col.tool"
  | "report.ops.empty"
  | "report.ops.title"
  | "report.print"
  | "report.save_markdown"
  | "report.source.all_geometry"
  | "report.source.no_layers"
  | "report.source.objects"
  | "report.stats.empty"
  | "report.stats.enabled_ops"
  | "report.stats.objects"
  | "report.stats.offsets"
  | "report.stats.segments"
  | "report.stats.title"
  | "report.status.error"
  | "report.status.not_generated"
  | "report.status.ok"
  | "report.status.pause"
  | "report.status.warnings"
  | "report.time.arc"
  | "report.time.cut"
  | "report.time.plunge"
  | "report.time.rapid"
  | "report.time.retract"
  | "report.time.spindle_warmup"
  | "report.time.title"
  | "report.time.tool_change"
  | "report.time.total"
  | "report.title"
  | "report.tools.col.diameter"
  | "report.tools.col.feed"
  | "report.tools.col.kind"
  | "report.tools.col.name"
  | "report.tools.col.speed"
  | "report.tools.empty"
  | "report.tools.title"
  | "report.untitled_project"
  | "report.warnings.summary"
  | "report.warnings.title"
  | "scene3d.ctx.dismiss"
  | "scene3d.ctx.hint"
  | "scene3d.ctx.new_op"
  | "scene3d.empty.sub"
  | "scene3d.empty.title"
  | "settings.appearance.language"
  | "settings.appearance.language.auto"
  | "settings.appearance.language.help"
  | "settings.appearance.theme"
  | "settings.appearance.theme.auto"
  | "settings.appearance.theme.dark"
  | "settings.appearance.theme.light"
  | "settings.group.appearance"
  | "settings.group.performance"
  | "settings.group.preview"
  | "settings.group.safety"
  | "settings.group.snap"
  | "settings.group.sources"
  | "settings.group.view"
  | "settings.group_nav.aria"
  | "settings.performance.caps_hint"
  | "settings.performance.exact_rewind"
  | "settings.performance.exact_rewind.hint"
  | "settings.performance.max_render_triangles"
  | "settings.performance.max_sim_cells"
  | "settings.performance.solid_default"
  | "settings.preview.arrow_density"
  | "settings.preview.arrow_off"
  | "settings.preview.cell_resolution"
  | "settings.preview.cell_resolution.auto"
  | "settings.preview.cell_resolution.manual"
  | "settings.preview.cell_size"
  | "settings.preview.cell_size.title"
  | "settings.preview.deviation_overlay"
  | "settings.preview.deviation_overlay_help"
  | "settings.preview.deviation_tolerance"
  | "settings.preview.edge_color"
  | "settings.preview.edge_opacity"
  | "settings.preview.intro"
  | "settings.preview.line_width"
  | "settings.preview.solid_color"
  | "settings.preview.solid_opacity"
  | "settings.safety.auto_regenerate"
  | "settings.safety.auto_regenerate.title"
  | "settings.safety.auto_run_sim"
  | "settings.safety.block_critical"
  | "settings.safety.block_work_area"
  | "settings.safety.block_work_area.title"
  | "settings.safety.hint"
  | "settings.snap.center"
  | "settings.snap.center.help"
  | "settings.snap.endpoint"
  | "settings.snap.endpoint.help"
  | "settings.snap.grid"
  | "settings.snap.grid.help"
  | "settings.snap.grid_step"
  | "settings.snap.grid_step.title"
  | "settings.snap.hint"
  | "settings.snap.intersection"
  | "settings.snap.intersection.help"
  | "settings.snap.midpoint"
  | "settings.snap.midpoint.help"
  | "settings.sources.auto_reload"
  | "settings.sources.hint"
  | "settings.title"
  | "settings.view.preview_style"
  | "settings.view.preview_style.both"
  | "settings.view.preview_style.solid"
  | "settings.view.preview_style.wireframe"
  | "settings.view.show_stock_box"
  | "shortcuts.canvas2d.add_selection"
  | "shortcuts.canvas2d.context"
  | "shortcuts.canvas2d.pan"
  | "shortcuts.canvas2d.remove_selection"
  | "shortcuts.canvas2d.select"
  | "shortcuts.global.add_text"
  | "shortcuts.global.escape"
  | "shortcuts.global.redo"
  | "shortcuts.global.show_help"
  | "shortcuts.global.undo"
  | "shortcuts.section.canvas2d"
  | "shortcuts.section.global"
  | "shortcuts.section.touch"
  | "shortcuts.section.view3d"
  | "shortcuts.title"
  | "shortcuts.touch.bottom_handles"
  | "shortcuts.touch.edge_swipe"
  | "shortcuts.touch.fit_view"
  | "shortcuts.touch.long_press"
  | "shortcuts.touch.multi_select"
  | "shortcuts.touch.one_finger"
  | "shortcuts.touch.pinch"
  | "shortcuts.touch.pull_down"
  | "shortcuts.touch.tap"
  | "shortcuts.touch.two_finger"
  | "shortcuts.view3d.orbit"
  | "shortcuts.view3d.pan"
  | "shortcuts.zoom"
  | "stock.dimensions"
  | "stock.flip"
  | "stock.flip.axis"
  | "stock.flip.axis.x"
  | "stock.flip.axis.x.hint"
  | "stock.flip.axis.y"
  | "stock.flip.axis.y.hint"
  | "stock.flip.badge"
  | "stock.flip.dowel_count"
  | "stock.flip.dowel_dia"
  | "stock.flip.dowel_margin"
  | "stock.flip.dowel_margin.title"
  | "stock.flip.enable"
  | "stock.length"
  | "stock.margin"
  | "stock.margin.title"
  | "stock.mode"
  | "stock.mode.auto"
  | "stock.mode.manual"
  | "stock.offset_z.title"
  | "stock.origin_offset"
  | "stock.snap_bbox"
  | "stock.snap_bbox.title"
  | "stock.thickness"
  | "stock.wcs"
  | "stock.width"
  | "stock.work_origin"
  | "stock.work_origin.title"
  | "textlist.activate.aria"
  | "textlist.add"
  | "textlist.add.aria"
  | "textlist.add.title"
  | "textlist.align.center"
  | "textlist.align.left"
  | "textlist.align.right"
  | "textlist.collapse.aria"
  | "textlist.collapse.title"
  | "textlist.delete.aria"
  | "textlist.delete.title"
  | "textlist.empty"
  | "textlist.expand.title"
  | "textlist.field.align"
  | "textlist.field.font"
  | "textlist.field.letter_gap"
  | "textlist.field.line_spacing"
  | "textlist.field.rotation"
  | "textlist.field.size"
  | "textlist.field.text"
  | "textlist.field.width"
  | "textlist.field.width.title"
  | "textlist.field.x"
  | "textlist.field.y"
  | "textlist.snap_origin"
  | "textlist.snap_origin.title"
  | "textlist.snap_origin.title_disabled"
  | "textlist.title"
  | "textlist.toggle_form.aria"
  | "toast.dismiss"
  | "toast.queue.more"
  | "toast.queue.title"
  | "toast.report_bug"
  | "toolform.add_row"
  | "toolform.angle"
  | "toolform.angle.title"
  | "toolform.cut_height"
  | "toolform.cut_height.title"
  | "toolform.delete_row.title"
  | "toolform.dovetail_dia"
  | "toolform.dovetail_dia.title"
  | "toolform.form_profile"
  | "toolform.form_profile.title"
  | "toolform.generate_dovetail"
  | "toolform.generate_dovetail.title"
  | "toolform.generate_tslot"
  | "toolform.generate_tslot.title"
  | "toolform.head_thick"
  | "toolform.head_thick.title"
  | "toolform.min_rows_hint"
  | "toolform.neck_dia"
  | "toolform.neck_dia.title"
  | "toolform.neck_length"
  | "toolform.neck_length.title"
  | "toolform.radius"
  | "toolform.tslot_head_dia"
  | "toolform.tslot_head_dia.title"
  | "toolform.z_above_tip"
  | "tools.add"
  | "tools.apply.invalid.title"
  | "tools.bullnose"
  | "tools.bullnose.corner_radius"
  | "tools.bullnose.corner_radius.title"
  | "tools.bullnose.title"
  | "tools.clear_filters"
  | "tools.col.coolant"
  | "tools.col.dflt_step"
  | "tools.col.dflt_step.title"
  | "tools.col.diameter.title"
  | "tools.col.feed"
  | "tools.col.feed.title"
  | "tools.col.flutes"
  | "tools.col.flutes.title"
  | "tools.col.id.title"
  | "tools.col.kind"
  | "tools.col.kind.title"
  | "tools.col.name"
  | "tools.col.name.title"
  | "tools.col.plunge"
  | "tools.col.plunge.title"
  | "tools.col.speed"
  | "tools.col.speed.title"
  | "tools.col.tip_angle"
  | "tools.col.tip_angle.title"
  | "tools.col.tip_diameter"
  | "tools.comment"
  | "tools.comment.placeholder"
  | "tools.comment.title"
  | "tools.compression"
  | "tools.compression.title"
  | "tools.compression.transition"
  | "tools.compression.transition.placeholder"
  | "tools.compression.transition.title"
  | "tools.coolant.flood"
  | "tools.coolant.mist"
  | "tools.coolant.off"
  | "tools.count.filtered"
  | "tools.count.many"
  | "tools.count.one"
  | "tools.drag"
  | "tools.drag.offset"
  | "tools.drag.offset.title"
  | "tools.drag.self_align"
  | "tools.drag.self_align.title"
  | "tools.drag.title"
  | "tools.drill.feed"
  | "tools.drill.peck"
  | "tools.drill.peck.title"
  | "tools.drill.plunge"
  | "tools.drill.rpm"
  | "tools.drill.xy_overlap"
  | "tools.drill.xy_overlap.title"
  | "tools.field.na"
  | "tools.file.load_add"
  | "tools.file.load_add.title"
  | "tools.file.load_replace"
  | "tools.file.load_replace.inventory.title"
  | "tools.file.load_replace.project.title"
  | "tools.file.save.inventory.title"
  | "tools.file.save.project.title"
  | "tools.filter.all"
  | "tools.filter.clear"
  | "tools.filter.kind"
  | "tools.filter.runs_on"
  | "tools.filter.runs_on.any"
  | "tools.filter.runs_on.drag"
  | "tools.filter.runs_on.laser"
  | "tools.filter.runs_on.mill"
  | "tools.filter.runs_on.plasma"
  | "tools.filter.runs_on.title"
  | "tools.finish.feed"
  | "tools.finish.plunge"
  | "tools.finish.rpm"
  | "tools.hidden.many"
  | "tools.hidden.one"
  | "tools.hide_incompatible"
  | "tools.holder.cone.bottom_diameter"
  | "tools.holder.cone.top_diameter"
  | "tools.holder.cyl.diameter"
  | "tools.holder.flute_length"
  | "tools.holder.flute_length.title"
  | "tools.holder.kind.cone"
  | "tools.holder.kind.cylinder"
  | "tools.holder.kind.none"
  | "tools.holder.kind.stepped"
  | "tools.holder.label"
  | "tools.holder.length"
  | "tools.holder.overall_length"
  | "tools.holder.overall_length.title"
  | "tools.holder.preset"
  | "tools.holder.preset.apply"
  | "tools.holder.preset.title"
  | "tools.holder.runs_on"
  | "tools.holder.runs_on.title"
  | "tools.holder.shank_diameter"
  | "tools.holder.shank_diameter.placeholder"
  | "tools.holder.shank_diameter.title"
  | "tools.holder.stepped.cone_length"
  | "tools.holder.stepped.cone_top_diameter"
  | "tools.holder.stepped.cyl_diameter"
  | "tools.holder.stepped.cyl_length"
  | "tools.holder.stickout"
  | "tools.holder.stickout.title"
  | "tools.laser"
  | "tools.laser.kerf"
  | "tools.laser.kerf.title"
  | "tools.laser.lead_in"
  | "tools.laser.lead_in.title"
  | "tools.laser.pierce_time"
  | "tools.laser.pierce_time.title"
  | "tools.laser.title"
  | "tools.no_match"
  | "tools.pager.next"
  | "tools.pager.prev"
  | "tools.pager.status"
  | "tools.pass_overrides"
  | "tools.pass_overrides.title"
  | "tools.plasma"
  | "tools.plasma.cut_height"
  | "tools.plasma.cut_height.title"
  | "tools.plasma.kerf"
  | "tools.plasma.kerf.title"
  | "tools.plasma.pierce_delay"
  | "tools.plasma.pierce_delay.title"
  | "tools.plasma.pierce_height"
  | "tools.plasma.pierce_height.title"
  | "tools.plasma.title"
  | "tools.row.delete.aria"
  | "tools.row.delete.disabled"
  | "tools.row.delete.title"
  | "tools.row.dflt_step.invalid.title"
  | "tools.row.dflt_step.title"
  | "tools.row.diameter.invalid.title"
  | "tools.row.expand.collapse.aria"
  | "tools.row.expand.collapse.title"
  | "tools.row.expand.expand.aria"
  | "tools.row.expand.expand.title"
  | "tools.row.feed.drill.title"
  | "tools.row.feed.invalid.title"
  | "tools.row.name.title"
  | "tools.row.plunge.invalid.title"
  | "tools.row.speed.invalid.title"
  | "tools.row.tip_angle.title"
  | "tools.row.tip_diameter.invalid.title"
  | "tools.save.invalid.title"
  | "tools.search.placeholder"
  | "tools.search.title"
  | "tools.show_all"
  | "tools.show_all.title"
  | "tools.showing_all"
  | "tools.spindle_dir"
  | "tools.spindle_dir.ccw"
  | "tools.spindle_dir.cw"
  | "tools.spindle_dir.disabled.drag_knife"
  | "tools.spindle_dir.disabled.laser"
  | "tools.spindle_dir.disabled.plasma"
  | "tools.spindle_dir.title"
  | "tools.spindle_warmup"
  | "tools.spindle_warmup.title"
  | "tools.thread"
  | "tools.thread.pitch"
  | "tools.thread.pitch.title"
  | "tools.thread.title"
  | "tools.title"
  | "tools.validation_msg"
  | "tools.wear"
  | "tools.wear.calibrate"
  | "tools.wear.calibrate.title"
  | "tools.wear.cuts_as"
  | "tools.wear.last_calibrated"
  | "tools.wear.never"
  | "tools.wear.offset"
  | "tools.wear.offset.title"
  | "tools.wear.stale"
  | "tools.wear.stale.title"
  | "tools.wear.title"
  | "tools.whirl"
  | "tools.whirl.enable"
  | "tools.whirl.extra_width"
  | "tools.whirl.extra_width.title"
  | "tools.whirl.stride"
  | "tools.whirl.stride.title"
  | "tools.whirl.title"
  | "tools.whirl.z_wobble"
  | "tools.whirl.z_wobble.title"
  | "tools.z_shift"
  | "tools.z_shift.title"
  | "warn.chamfer_non_vbit"
  | "warn.chamfer_width_clamped_to_reach"
  | "warn.compression_transition_above_cut"
  | "warn.cps_unsupported_op"
  | "warn.dovetail_requires_rough_channel.generic"
  | "warn.dovetail_requires_rough_channel.known"
  | "warn.drill_spot_depth_non_negative"
  | "warn.drill_spot_tool_missing"
  | "warn.dual_tool_no_toolchange"
  | "warn.feed_clamped_above_max"
  | "warn.fixed_sensor_reference_not_first"
  | "warn.frame_padding_below_tool_radius"
  | "warn.gcode_include_empty"
  | "warn.gcode_include_lines_skipped"
  | "warn.gcode_include_unknown_variable"
  | "warn.gcode_include_unsim_line"
  | "warn.grbl_atc_no_toolchange_template"
  | "warn.grbl_fixed_sensor_no_offset"
  | "warn.halfpipe_depth_limited"
  | "warn.halfpipe_radius_mismatch"
  | "warn.halfpipe_tool_reach_exceeded"
  | "warn.helix_radius_unfittable"
  | "warn.multi_tool_manual_machine"
  | "warn.nocontour_ignores_finish_allowance"
  | "warn.op_machine_mode_mismatch"
  | "warn.op_order_suspect.drill_after_profile"
  | "warn.op_order_suspect.finish_before_rough"
  | "warn.op_source_empty.layer"
  | "warn.op_source_empty.object"
  | "warn.op_source_missing_layer"
  | "warn.op_source_missing_object"
  | "warn.out_of_stock"
  | "warn.out_of_stock.at_line"
  | "warn.out_of_work_area"
  | "warn.out_of_work_area.at_line"
  | "warn.parallel_offset_panicked"
  | "warn.pierce_on_contour_no_lead.laser"
  | "warn.pierce_on_contour_no_lead.plasma"
  | "warn.plunge_overridden"
  | "warn.pocket_cascade_truncated"
  | "warn.pocket_fill_incomplete"
  | "warn.ramp_arcs_at_boundary"
  | "warn.raster_too_large"
  | "warn.relief_missing_roughing"
  | "warn.relief_source_invalid"
  | "warn.relief_tool_reach_exceeded"
  | "warn.rotate_offsets_far_from_approach"
  | "warn.spindle_speed_clamped_above_max"
  | "warn.spindle_speed_clamped_below_min"
  | "warn.step_unspecified"
  | "warn.stock_origin_outside_geometry_bbox"
  | "warn.stufenfase_no_toolchange"
  | "warn.stufenfase_non_circle_skipped"
  | "warn.tabs_count_clamped_short_contour"
  | "warn.tabs_with_trochoidal_unsupported"
  | "warn.thread_dz_less_than_pitch"
  | "warn.thread_no_circles"
  | "warn.thread_no_depth"
  | "warn.thread_tool_too_large"
  | "warn.thread_whirl_radius_clamped"
  | "warn.thread_zero_bore"
  | "warn.tool_geometry_impossible"
  | "warn.tool_incompatible_with_machine_mode"
  | "warn.tool_kind_mismatch.dovetail_non_form"
  | "warn.tool_kind_mismatch.halfpipe_circular_arc"
  | "warn.tool_kind_mismatch.halfpipe_vbottom"
  | "warn.tool_kind_mismatch.pocket_dragknife"
  | "warn.tool_kind_mismatch.pocket_drill"
  | "warn.tool_kind_mismatch.profile_drill"
  | "warn.tool_kind_mismatch.relief_non_round"
  | "warn.tool_kind_mismatch.thread_dragknife"
  | "warn.tool_kind_mismatch.thread_drill"
  | "warn.tool_kind_mismatch.thread_laser"
  | "warn.tool_kind_mismatch.tslot_non_form"
  | "warn.tool_kind_mismatch.vcarve_non_vbit"
  | "warn.tool_tip_angle_clamped"
  | "warn.tool_too_large"
  | "warn.trochoidal_incomplete"
  | "warn.tslot_requires_stem_slot.generic"
  | "warn.tslot_requires_stem_slot.known"
  | "warn.two_sided_overlap"
  | "warn.vcarve_below_tip_radius.full_none"
  | "warn.vcarve_below_tip_radius.full_some"
  | "warn.vcarve_below_tip_radius.perimeter"
  | "warn.vcarve_depth_limited"
  | "warn.vcarve_no_closed_region"
  | "warn.vcarve_no_medial_axis"
  | "warn.zero_rate_emitted"
  | "warn.zigzag_stride_clamped_below_minimum";

/** All keys as an array (handy for coverage tests / iteration). */
export const MSG_KEYS: readonly MsgKey[] = [
  "about.build",
  "about.build_hint",
  "about.col.library",
  "about.col.license",
  "about.col.role",
  "about.copied",
  "about.copy",
  "about.copy_build_id.title",
  "about.date",
  "about.date.title",
  "about.logo_alt",
  "about.third_party",
  "about.third_party.intro",
  "about.title",
  "app.bar.open",
  "app.bar.save",
  "app.drop.sub",
  "app.drop.title",
  "app.gcode.label",
  "app.gcode.lines",
  "app.gcode.toggle_tip",
  "app.loading.about",
  "app.loading.gcode",
  "app.loading.machine",
  "app.loading.settings",
  "app.loading.threed",
  "app.loading.tools",
  "app.panel.back",
  "app.redo.aria",
  "app.redo.none",
  "app.redo.tip",
  "app.regions.label",
  "app.regions.tip",
  "app.report.aria",
  "app.report.tip",
  "app.save.carved_stl",
  "app.save.carved_stl_solid",
  "app.save.carved_stl_solid.title",
  "app.save.close_menu",
  "app.save.gcode",
  "app.save.gcode_back",
  "app.save.gcode_front",
  "app.save.options",
  "app.save.project",
  "app.screen.close_menu",
  "app.screen.goto",
  "app.screen.label",
  "app.screen.next",
  "app.screen.prev",
  "app.sheet.gcode",
  "app.sheet.operations",
  "app.sheet.stock_layers",
  "app.splitter.gcode_tip",
  "app.splitter.sidebar_tip",
  "app.status.hints_idle",
  "app.status.hints_selection",
  "app.status.object_many",
  "app.status.object_one",
  "app.status.pick_approach",
  "app.status.ready",
  "app.status.tab_placement",
  "app.stock.collapse",
  "app.stock.collapse_prev",
  "app.stock.dims_tip",
  "app.stock.dims_tip_current",
  "app.stock.expand",
  "app.stock.name",
  "app.tab.about",
  "app.tab.about_tip",
  "app.tab.areas",
  "app.tab.help",
  "app.tab.help_tip",
  "app.tab.machine",
  "app.tab.machine_tip",
  "app.tab.project",
  "app.tab.settings",
  "app.tab.settings_tip",
  "app.tab.tools",
  "app.tab.tools_tip",
  "app.toolbar.open_tip",
  "app.toolbar.save_tip",
  "app.undo.aria",
  "app.undo.none",
  "app.undo.tip",
  "app.viewport.mode",
  "app.viewport.threed_tip",
  "calib.current",
  "calib.implausible",
  "calib.invalid",
  "calib.measured_width",
  "calib.result",
  "calib.step.cut",
  "calib.step.enter",
  "calib.step.measure",
  "calib.title",
  "canvas.add_to_selection.aria",
  "canvas.add_to_selection.title",
  "canvas.ctx.dismiss",
  "canvas.ctx.empty_hint",
  "canvas.ctx.new_op_from_selection",
  "canvas.ctx.set_text_origin",
  "canvas.ctx.set_text_origin.title",
  "canvas.ctx.text_layer",
  "canvas.firstrun.click_select",
  "canvas.firstrun.longpress_op",
  "canvas.firstrun.multiselect",
  "canvas.firstrun.rightclick_op",
  "canvas.firstrun.tap_select",
  "canvas.fit_view.aria",
  "canvas.fit_view.title",
  "canvas.help.aria",
  "canvas.help.title",
  "canvas.selection_hud",
  "canvas.snap_off",
  "canvas.tab_popover.delete",
  "canvas.tab_popover.header",
  "canvas.tab_popover.height",
  "canvas.tab_popover.width",
  "common.apply",
  "common.cancel",
  "common.close",
  "common.discard",
  "common.discard_unsaved",
  "common.done",
  "common.keep_editing",
  "common.load_ellipsis",
  "common.ok",
  "common.revert",
  "common.save_ellipsis",
  "dialog.action.load_recent_project",
  "dialog.action.load_sample",
  "dialog.action.open_another_file",
  "dialog.action.open_another_project",
  "dialog.action.open_dropped_drawing",
  "dialog.action.open_dropped_project",
  "dialog.export_stl.no_stock",
  "dialog.loading.dxf",
  "dialog.loading.file",
  "dialog.loading.gcode",
  "dialog.loading.hpgl",
  "dialog.loading.project",
  "dialog.loading.sample",
  "dialog.loading.stl",
  "dialog.loading.svg",
  "dialog.open_drawing.add_to_layers",
  "dialog.open_drawing.body",
  "dialog.open_drawing.new_project",
  "dialog.open_drawing.title",
  "dialog.quit.confirm_body",
  "dialog.quit.discard_quit",
  "dialog.quit.quit",
  "dialog.quit.save_quit",
  "dialog.quit.title",
  "dialog.quit.unsaved_body",
  "dialog.text.add",
  "dialog.text.depth",
  "dialog.text.depth.title",
  "dialog.text.discard_prompt",
  "dialog.text.engraving_mismatch",
  "dialog.text.error.empty",
  "dialog.text.error.no_engraving_font",
  "dialog.text.error.no_font",
  "dialog.text.font",
  "dialog.text.font.bundled.title",
  "dialog.text.font.custom.title",
  "dialog.text.font.loaded",
  "dialog.text.font.single_line_suffix",
  "dialog.text.no_tool",
  "dialog.text.pos_x",
  "dialog.text.pos_x.title",
  "dialog.text.pos_y",
  "dialog.text.pos_y.title",
  "dialog.text.size",
  "dialog.text.size.title",
  "dialog.text.style",
  "dialog.text.style.carve_inside",
  "dialog.text.style.carve_inside.help",
  "dialog.text.style.engraving",
  "dialog.text.style.engraving.help",
  "dialog.text.style.outline_inside",
  "dialog.text.style.outline_inside.help",
  "dialog.text.style.outline_outside",
  "dialog.text.style.outline_outside.help",
  "dialog.text.style.plain",
  "dialog.text.style.plain.help",
  "dialog.text.style.pocket_inside",
  "dialog.text.style.pocket_inside.help",
  "dialog.text.style.pocket_outside",
  "dialog.text.style.pocket_outside.help",
  "dialog.text.switch_font",
  "dialog.text.text",
  "dialog.text.text.title",
  "dialog.text.title",
  "dialog.text.tool",
  "dialog.text.tool.title",
  "dialog.text.width",
  "dialog.text.width.title",
  "dialog.unsaved.body",
  "dialog.unsaved.dont_save",
  "dialog.unsaved.save_continue",
  "dialog.unsaved.title",
  "error.code.cps_post_failed",
  "error.code.cps_selection_missing",
  "error.code.cps_unavailable",
  "error.code.internal_panic",
  "error.code.missing_tool",
  "error.code.text_render_failed",
  "error.code.two_sided_through",
  "error.code.unimplemented_op_kind",
  "error.code.unknown_post_processor",
  "error.fix.apply",
  "error.fix.assign_tool",
  "error.fix.change_profile_offset",
  "error.fix.disable_op",
  "error.fix.lower_sim_resolution",
  "error.hint.cps_post_failed",
  "error.hint.cps_selection_missing",
  "error.hint.cps_unavailable",
  "error.hint.internal_panic",
  "error.hint.missing_tool",
  "error.hint.text_render_failed",
  "error.hint.two_sided_through",
  "error.hint.unimplemented_op_kind",
  "error.hint.unknown_post_processor",
  "error.span",
  "gcode.label",
  "gcode.line_sync_unavailable",
  "gcode.line_sync_unavailable.title",
  "gcode.silenced",
  "gcode.silenced.title",
  "gcode.stale",
  "gcode.stale.title",
  "gcode.tab.back",
  "gcode.tab.front",
  "gcode.tab.readonly",
  "gcode.tab.readonly.title",
  "gcode.tab.title",
  "genbar.chip.clean",
  "genbar.chip.critical",
  "genbar.chip.details_title",
  "genbar.chip.idle",
  "genbar.chip.stale",
  "genbar.chip.warnings",
  "genbar.download.back",
  "genbar.download.front",
  "genbar.download.ngc",
  "genbar.download.plt",
  "genbar.download.stl_title",
  "genbar.download.title",
  "genbar.error.block_critical",
  "genbar.error.block_work_area",
  "genbar.error.cps_post_missing",
  "genbar.error.no_operations",
  "genbar.generate.generate",
  "genbar.generate.generating",
  "genbar.generate.regenerate",
  "genbar.generate.title",
  "genbar.generate.title_stale",
  "genbar.panel.aria",
  "genbar.panel.empty",
  "genbar.panel.title",
  "genbar.row.apply_fix",
  "genbar.row.apply_fix_aria",
  "genbar.row.apply_fix_title",
  "genbar.row.goto",
  "genbar.row.goto_aria",
  "genbar.row.goto_title",
  "genbar.row.pipeline",
  "genbar.row.pipeline_title",
  "genbar.row.sim",
  "genbar.row.sim_title",
  "genbar.sim_idle_hint",
  "genbar.source_stale.changed",
  "genbar.source_stale.reload",
  "genbar.source_stale.title",
  "genbar.stats.cached",
  "genbar.stats.summary",
  "genbar.time.arc",
  "genbar.time.aria",
  "genbar.time.cut",
  "genbar.time.plunge",
  "genbar.time.rapid",
  "genbar.time.retract",
  "genbar.time.spindle_warmup",
  "genbar.time.toolchange",
  "genbar.time.total",
  "layers.add",
  "layers.add.open_file",
  "layers.add.open_file.title",
  "layers.add.text",
  "layers.add.text.title",
  "layers.add.title",
  "layers.caret.collapse.aria",
  "layers.caret.collapse.title",
  "layers.caret.expand.aria",
  "layers.caret.expand.title",
  "layers.drawings",
  "layers.empty.open_file",
  "layers.empty.sub",
  "layers.empty.title",
  "layers.file_stats",
  "layers.file_stats.title",
  "layers.import_remove.aria",
  "layers.import_remove.title",
  "layers.import_stats",
  "layers.reopen.accept",
  "layers.reopen.dismiss",
  "layers.reopen.prefix",
  "layers.reopen.suffix",
  "layers.row.delete.aria",
  "layers.row.delete.title",
  "layers.row.toggle.title",
  "layers.title",
  "layers.toggle_all.aria",
  "layers.toggle_all.title",
  "layers.xform.active.aria",
  "layers.xform.head.title",
  "layers.xform.label",
  "layers.xform.mirror_x",
  "layers.xform.mirror_x.title",
  "layers.xform.mirror_y",
  "layers.xform.mirror_y.title",
  "layers.xform.reset",
  "layers.xform.reset.title",
  "layers.xform.rotate",
  "layers.xform.rotate.title",
  "layers.xform.scale",
  "layers.xform.scale.title",
  "layers.xform.tx.title",
  "layers.xform.ty.title",
  "machine.accel.x.aria",
  "machine.accel.y.aria",
  "machine.accel.z.aria",
  "machine.accel_label",
  "machine.arc_tol",
  "machine.arc_tol.title",
  "machine.cap.drag",
  "machine.cap.laser",
  "machine.cap.mill",
  "machine.cap.plasma",
  "machine.capabilities",
  "machine.capabilities.legend_title",
  "machine.capabilities.primary_title",
  "machine.cps.open_file",
  "machine.cps.post",
  "machine.cps.post.none",
  "machine.cps.post.title",
  "machine.cps.properties",
  "machine.cps.unsupported",
  "machine.decimal_sep",
  "machine.decimal_sep.comma",
  "machine.decimal_sep.period",
  "machine.decimal_sep.title",
  "machine.dialect",
  "machine.dialect.cps",
  "machine.dialect.title",
  "machine.emit_arcs",
  "machine.emit_arcs.title",
  "machine.emit_comments",
  "machine.emit_comments.title",
  "machine.fast_move_z",
  "machine.fast_move_z.title",
  "machine.hpgl_note",
  "machine.jerk.x.aria",
  "machine.jerk.y.aria",
  "machine.jerk.z.aria",
  "machine.jerk_enable",
  "machine.jerk_enable.title",
  "machine.jerk_label",
  "machine.laser_dynamic",
  "machine.laser_dynamic.title",
  "machine.line_num",
  "machine.line_num.placeholder",
  "machine.line_num.title",
  "machine.load.title",
  "machine.max_feed",
  "machine.max_feed.title",
  "machine.mode",
  "machine.mode.drag",
  "machine.mode.laser",
  "machine.mode.mill",
  "machine.mode.plasma",
  "machine.mode.title",
  "machine.name",
  "machine.name.input_title",
  "machine.name.label_title",
  "machine.optional_stop",
  "machine.optional_stop.title",
  "machine.park.x.aria",
  "machine.park.y.aria",
  "machine.park_home",
  "machine.park_home.title",
  "machine.park_xy.help",
  "machine.park_xy_label",
  "machine.plot_mode",
  "machine.plot_mode.title",
  "machine.pp.edit_btn",
  "machine.pp.no_overrides",
  "machine.pp.overrides",
  "machine.pp.tweak.axes",
  "machine.pp.tweak.coolant",
  "machine.pp.tweak.file",
  "machine.pp.tweak.footer",
  "machine.pp.tweak.header",
  "machine.pp.tweak.mist",
  "machine.pp.tweak.toolchange",
  "machine.profile.delete",
  "machine.profile.delete.title",
  "machine.profile.delete_confirm",
  "machine.profile.dirty_switch.title",
  "machine.profile.duplicate",
  "machine.profile.duplicate.title",
  "machine.profile.label",
  "machine.profile.missing_note",
  "machine.profile.missing_note.title",
  "machine.profile.none_option",
  "machine.profile.pick.title",
  "machine.profile.referenced_missing_option",
  "machine.profile.save_as",
  "machine.profile.save_as.title",
  "machine.profile_preset",
  "machine.profile_preset.custom",
  "machine.profile_preset.grbl",
  "machine.profile_preset.linuxcnc",
  "machine.profile_preset.mach3",
  "machine.profile_preset.none",
  "machine.profile_preset.title",
  "machine.rapid",
  "machine.rapid.title",
  "machine.save.title",
  "machine.section.gcode_formatting",
  "machine.section.kinematics",
  "machine.section.post_profile",
  "machine.section.spindle",
  "machine.spindle_max",
  "machine.spindle_max.title",
  "machine.spindle_min",
  "machine.spindle_min.title",
  "machine.spindle_start_dwell",
  "machine.spindle_start_dwell.title",
  "machine.spindle_stop_dwell",
  "machine.spindle_stop_dwell.title",
  "machine.storage_note",
  "machine.title",
  "machine.toolchange",
  "machine.toolchange.atc",
  "machine.toolchange.ignore",
  "machine.toolchange.m0_pause",
  "machine.toolchange.m6_prompt",
  "machine.toolchange.title",
  "machine.toolchange_time",
  "machine.toolchange_time.title",
  "machine.unit",
  "machine.unit.inch",
  "machine.unit.mm",
  "machine.unit.title",
  "machine.work_area",
  "machine.work_area.legend_title",
  "machinetool.add",
  "machinetool.add.title",
  "machinetool.already_stocked.title",
  "machinetool.filter.placeholder",
  "machinetool.filter.title",
  "machinetool.incompatible",
  "machinetool.incompatible.title",
  "machinetool.incompatible_tool.title",
  "machinetool.inventory_empty",
  "machinetool.remove",
  "machinetool.remove.title",
  "machinetool.remove_last.title",
  "machinetool.remove_used.title.one",
  "machinetool.remove_used.title.other",
  "machinetool.shop_inventory",
  "machinetool.shop_inventory.title",
  "machinetool.stocked",
  "machinetool.stocked_col",
  "machinetool.stocked_col.title",
  "machinews.delete",
  "machinews.delete.confirm",
  "machinews.delete.title",
  "machinews.duplicate",
  "machinews.duplicate.title",
  "machinews.load_file",
  "machinews.load_file.title",
  "machinews.machine",
  "machinews.missing",
  "machinews.missing.title",
  "machinews.new",
  "machinews.new.title",
  "machinews.pick.title",
  "machinews.project_local",
  "machinews.referenced_missing",
  "machinews.save_file",
  "machinews.save_file.title",
  "machinews.sections.aria",
  "machinews.settings",
  "machinews.settings.title",
  "machinews.tooling",
  "machinews.tooling.title",
  "menu.aria.more_actions",
  "menu.aria.trigger",
  "menu.exit",
  "menu.no_recent",
  "menu.open",
  "menu.recent_projects",
  "menu.redo",
  "menu.report",
  "menu.save_gcode",
  "menu.save_gcode_back",
  "menu.save_gcode_front",
  "menu.save_project",
  "menu.save_stl",
  "menu.show_regions",
  "menu.undo",
  "modeswitch.add_default",
  "modeswitch.affected.many",
  "modeswitch.affected.one",
  "modeswitch.assign.all",
  "modeswitch.assign.one",
  "modeswitch.dismiss.aria",
  "modeswitch.dismiss.title",
  "modeswitch.none",
  "oplist.activate.aria",
  "oplist.add.aria",
  "oplist.add.title",
  "oplist.collapse.aria",
  "oplist.collapse.title",
  "oplist.count.title",
  "oplist.delete.aria",
  "oplist.delete.title",
  "oplist.duplicate.aria",
  "oplist.duplicate.title",
  "oplist.empty.cta",
  "oplist.empty.sub",
  "oplist.empty.title",
  "oplist.expand.title",
  "oplist.filter.all",
  "oplist.filter.empty",
  "oplist.filter.title",
  "oplist.grip.title",
  "oplist.group_by_tool",
  "oplist.group_by_tool.title",
  "oplist.repick",
  "oplist.repick.aria",
  "oplist.repick.layers_suffix",
  "oplist.repick.title_empty",
  "oplist.repick.title_ready",
  "oplist.side.back",
  "oplist.side.count.title",
  "oplist.side.front",
  "oplist.status.cycle_marker",
  "oplist.status.dirty",
  "oplist.status.gcode_include",
  "oplist.status.homing",
  "oplist.status.no_drawing",
  "oplist.status.not_generated",
  "oplist.status.orphan_layers",
  "oplist.status.orphan_objects",
  "oplist.status.pause",
  "oplist.status.probe",
  "oplist.status.tool_missing",
  "oplist.status.up_to_date",
  "oplist.status_btn.aria",
  "oplist.status_btn.title",
  "oplist.title",
  "oplist.tool_missing",
  "opprops.combine",
  "opprops.combine.auto",
  "opprops.combine.auto.help",
  "opprops.combine.difference",
  "opprops.combine.difference.help",
  "opprops.combine.intersection",
  "opprops.combine.intersection.help",
  "opprops.combine.none",
  "opprops.combine.none.help",
  "opprops.combine.union",
  "opprops.combine.union.help",
  "opprops.combine.xor",
  "opprops.combine.xor.help",
  "opprops.cut",
  "opprops.cut.approach_point",
  "opprops.cut.approach_point.clear",
  "opprops.cut.approach_point.clear.title",
  "opprops.cut.approach_point.pick",
  "opprops.cut.approach_point.pick.title",
  "opprops.cut.approach_point.picking",
  "opprops.cut.approach_point.picking.title",
  "opprops.cut.approach_point.title",
  "opprops.cut.approach_point.x_aria",
  "opprops.cut.approach_point.y_aria",
  "opprops.cut.depth_list",
  "opprops.cut.depth_list.placeholder",
  "opprops.cut.depth_list.title",
  "opprops.cut.direction",
  "opprops.cut.final_depth",
  "opprops.cut.finish_direction",
  "opprops.cut.finish_step",
  "opprops.cut.finish_step.placeholder",
  "opprops.cut.finish_step.title",
  "opprops.cut.plunge",
  "opprops.cut.start_depth",
  "opprops.cut.step",
  "opprops.cut.step.from_tool",
  "opprops.cut.step.required",
  "opprops.cut.step.reset",
  "opprops.cut.step.reset.title",
  "opprops.cut.through_depth",
  "opprops.cut.through_depth.title",
  "opprops.cut.xy_finish_stock",
  "opprops.cut.xy_finish_stock.title",
  "opprops.direction.climb",
  "opprops.direction.climb.help",
  "opprops.direction.conventional",
  "opprops.direction.conventional.help",
  "opprops.empty",
  "opprops.feeds",
  "opprops.feeds.corner_slow",
  "opprops.feeds.corner_slow.title",
  "opprops.feeds.custom",
  "opprops.feeds.feed_rate",
  "opprops.feeds.feed_rate.reset.title",
  "opprops.feeds.feed_rate.title",
  "opprops.feeds.fraction",
  "opprops.feeds.fraction.title",
  "opprops.feeds.plunge_rate",
  "opprops.feeds.plunge_rate.reset.title",
  "opprops.feeds.plunge_rate.title",
  "opprops.feeds.reset",
  "opprops.feeds.tool_default",
  "opprops.feeds.tool_defaults",
  "opprops.finish_tool",
  "opprops.finish_tool.same_as_rough",
  "opprops.finish_tool.title.drill",
  "opprops.finish_tool.title.pocket",
  "opprops.from_selection",
  "opprops.from_selection.count",
  "opprops.from_selection.disabled_aria",
  "opprops.from_selection.title",
  "opprops.group",
  "opprops.group.label",
  "opprops.group.label.placeholder",
  "opprops.group.label.title",
  "opprops.group.none",
  "opprops.group.pin_order",
  "opprops.group.pin_order.title",
  "opprops.helix",
  "opprops.helix_angle",
  "opprops.helix_angle.title",
  "opprops.helix_autofit",
  "opprops.helix_autofit.title",
  "opprops.helix_radius",
  "opprops.helix_radius.auto.title",
  "opprops.helix_radius.auto_detected",
  "opprops.helix_radius.auto_no_fit",
  "opprops.helix_radius.auto_no_fit_reason",
  "opprops.helix_radius.auto_pending",
  "opprops.helix_radius.manual.title",
  "opprops.name",
  "opprops.pattern",
  "opprops.pattern.grid",
  "opprops.pattern.linear",
  "opprops.pattern.polar",
  "opprops.pattern.single",
  "opprops.plunge.direct",
  "opprops.plunge.direct.help",
  "opprops.plunge.helix",
  "opprops.plunge.helix.help",
  "opprops.plunge.ramp",
  "opprops.plunge.ramp.help",
  "opprops.ramp_angle",
  "opprops.ramp_angle.title",
  "opprops.side",
  "opprops.side.back",
  "opprops.side.front",
  "opprops.side.title",
  "opprops.source",
  "opprops.source.all_chains",
  "opprops.source.layer",
  "opprops.source.layer.pick",
  "opprops.source.mode",
  "opprops.source.mode.all",
  "opprops.source.mode.layer",
  "opprops.source.mode.objects",
  "opprops.source.objects_selected",
  "opprops.source.text_group",
  "opprops.tabs",
  "opprops.tabs.auto",
  "opprops.tabs.auto_manual",
  "opprops.tabs.manual",
  "opprops.tabs.off",
  "opprops.title",
  "opprops.tool",
  "opprops.tool.edit",
  "opprops.tool.incompatible_group",
  "opprops.tool.mismatch",
  "opprops.tool.mismatch.title",
  "opprops.tool.title.default",
  "opprops.tool.title.raster",
  "opprops.tool.title.relief",
  "opprops.wear.effective_diameter",
  "opprops.wear.title",
  "ops.chamfer.finish_pass.help",
  "ops.chamfer.finish_pass.label",
  "ops.chamfer.legend",
  "ops.chamfer.width.help",
  "ops.chamfer.width.label",
  "ops.cycle_marker.emits.hint",
  "ops.cycle_marker.label.help",
  "ops.cycle_marker.label.label",
  "ops.cycle_marker.label.placeholder",
  "ops.cycle_marker.name.label",
  "ops.cycle_marker.no_motion.hint",
  "ops.drill.chamfer_width.help",
  "ops.drill.chamfer_width.label",
  "ops.drill.cycle.chip_break",
  "ops.drill.cycle.chip_break.help",
  "ops.drill.cycle.label",
  "ops.drill.cycle.peck",
  "ops.drill.cycle.peck.help",
  "ops.drill.cycle.simple",
  "ops.drill.cycle.simple.help",
  "ops.drill.cycle_options",
  "ops.drill.dwell.label",
  "ops.drill.legend",
  "ops.drill.peck_step.label",
  "ops.drill.spot_depth.help",
  "ops.drill.spot_depth.label",
  "ops.drill.spot_first.help",
  "ops.drill.spot_first.label",
  "ops.drill.spot_options",
  "ops.drill.spot_tool.label",
  "ops.gcode_include.content.help",
  "ops.gcode_include.content.label",
  "ops.gcode_include.content.placeholder",
  "ops.gcode_include.file.help",
  "ops.gcode_include.file.label",
  "ops.gcode_include.loaded_from.hint",
  "ops.gcode_include.loaded_stats.hint",
  "ops.gcode_include.name.label",
  "ops.gcode_include.token_feed.hint",
  "ops.gcode_include.token_safez.hint",
  "ops.gcode_include.token_spindle.hint",
  "ops.gcode_include.token_xyz.hint",
  "ops.gcode_include.tokens_intro.hint",
  "ops.gcode_include.tokens_outro.hint",
  "ops.gcode_include.verbose_unsim_warnings.help",
  "ops.gcode_include.verbose_unsim_warnings.label",
  "ops.help.chamfer",
  "ops.help.cycle_marker",
  "ops.help.dovetail",
  "ops.help.drag_knife",
  "ops.help.drill",
  "ops.help.engrave",
  "ops.help.gcode_include",
  "ops.help.homing",
  "ops.help.pause",
  "ops.help.pocket",
  "ops.help.pocket_outside",
  "ops.help.probe",
  "ops.help.profile",
  "ops.help.raster_engrave",
  "ops.help.relief_mill",
  "ops.help.t_slot",
  "ops.help.thread",
  "ops.help.vcarve",
  "ops.help.waterline_rough",
  "ops.homing.name.label",
  "ops.homing.pipeline.hint_prefix",
  "ops.homing.pipeline.hint_suffix",
  "ops.homing.pipeline.safe_z_suffix",
  "ops.homing.retract_safe_z.help",
  "ops.homing.retract_safe_z.label",
  "ops.image.none_loaded",
  "ops.kind.chamfer",
  "ops.kind.cycle_marker",
  "ops.kind.dovetail",
  "ops.kind.drag_knife",
  "ops.kind.drill",
  "ops.kind.engrave",
  "ops.kind.gcode_include",
  "ops.kind.homing",
  "ops.kind.pause",
  "ops.kind.pocket",
  "ops.kind.pocket_outside",
  "ops.kind.probe",
  "ops.kind.profile",
  "ops.kind.raster_engrave",
  "ops.kind.relief_mill",
  "ops.kind.t_slot",
  "ops.kind.thread",
  "ops.kind.vcarve",
  "ops.kind.waterline_rough",
  "ops.pattern.center_x.help",
  "ops.pattern.center_x.label",
  "ops.pattern.center_y.help",
  "ops.pattern.center_y.label",
  "ops.pattern.count_x.help",
  "ops.pattern.count_x.label",
  "ops.pattern.count_y.help",
  "ops.pattern.count_y.label",
  "ops.pattern.grid_dx.help",
  "ops.pattern.grid_dy.help",
  "ops.pattern.intro.hint",
  "ops.pattern.kind.grid",
  "ops.pattern.kind.help",
  "ops.pattern.kind.label",
  "ops.pattern.kind.linear",
  "ops.pattern.kind.none",
  "ops.pattern.kind.polar",
  "ops.pattern.legend",
  "ops.pattern.linear_count.help",
  "ops.pattern.linear_count.label",
  "ops.pattern.linear_dx.help",
  "ops.pattern.linear_dy.help",
  "ops.pattern.polar_count.help",
  "ops.pattern.polar_count.label",
  "ops.pattern.set_center",
  "ops.pattern.set_center.disabled_help",
  "ops.pattern.set_center.help",
  "ops.pattern.start.help",
  "ops.pattern.start.label",
  "ops.pattern.step.help",
  "ops.pattern.step.label",
  "ops.pause.emits.hint",
  "ops.pause.emits_and.hint",
  "ops.pause.emits_message.hint",
  "ops.pause.emits_slot.hint",
  "ops.pause.message.help",
  "ops.pause.message.label",
  "ops.pause.message.placeholder",
  "ops.pause.name.label",
  "ops.picker.add_aria",
  "ops.picker.select_first",
  "ops.pocket.engagement_angle.help",
  "ops.pocket.engagement_angle.label",
  "ops.pocket.frame.legend",
  "ops.pocket.frame.shape.rectangle",
  "ops.pocket.frame.shape.rounded_rectangle",
  "ops.pocket.frame.summary",
  "ops.pocket.frame_corner_radius.help",
  "ops.pocket.frame_corner_radius.label",
  "ops.pocket.frame_corner_radius.placeholder",
  "ops.pocket.frame_padding.help",
  "ops.pocket.frame_padding.label",
  "ops.pocket.frame_shape.help",
  "ops.pocket.frame_shape.label",
  "ops.pocket.halfpipe.profile.circular_arc",
  "ops.pocket.halfpipe.profile.v_bottom",
  "ops.pocket.halfpipe.summary",
  "ops.pocket.halfpipe_profile.help",
  "ops.pocket.halfpipe_profile.hint",
  "ops.pocket.included_angle.help",
  "ops.pocket.included_angle.label",
  "ops.pocket.legend",
  "ops.pocket.loop_radius_factor.help",
  "ops.pocket.loop_radius_factor.label",
  "ops.pocket.outside.convert",
  "ops.pocket.outside.help",
  "ops.pocket.outside.hint",
  "ops.pocket.outside.legend",
  "ops.pocket.profile.help",
  "ops.pocket.profile.label",
  "ops.pocket.radius.help",
  "ops.pocket.radius.label",
  "ops.pocket.strategy.cascade",
  "ops.pocket.strategy.halfpipe",
  "ops.pocket.strategy.label",
  "ops.pocket.strategy.spiral",
  "ops.pocket.strategy.trochoidal",
  "ops.pocket.strategy.zigzag",
  "ops.pocket.trochoidal.summary",
  "ops.pocket.trochoidal_climb.hint",
  "ops.pocket.trochoidal_plunge.hint",
  "ops.pocket.trochoidal_tabs.hint",
  "ops.pocket.xy_overlap.help_empty",
  "ops.pocket.xy_overlap.help_set",
  "ops.pocket.xy_overlap.inherit_global",
  "ops.pocket.xy_overlap.inherit_tool",
  "ops.pocket.xy_overlap.label",
  "ops.pocket.xy_overlap.source_global",
  "ops.pocket.xy_overlap.source_tool",
  "ops.pocket.xy_overlap.unit_help",
  "ops.pocket.zigzag.summary",
  "ops.pocket.zigzag_angle.help",
  "ops.pocket.zigzag_angle.label",
  "ops.pocket.zigzag_angle_quick.help",
  "ops.probe.axis.help",
  "ops.probe.axis.label",
  "ops.probe.distance.help",
  "ops.probe.distance.label",
  "ops.probe.emits.hint",
  "ops.probe.feed.help",
  "ops.probe.feed.label",
  "ops.probe.halts.hint",
  "ops.probe.name.label",
  "ops.profile.lead.off",
  "ops.profile.lead.straight",
  "ops.profile.lead_in.arc",
  "ops.profile.lead_in.help",
  "ops.profile.lead_in.label",
  "ops.profile.lead_in_length.help",
  "ops.profile.lead_in_radius.help",
  "ops.profile.lead_out.arc",
  "ops.profile.lead_out.help",
  "ops.profile.lead_out.label",
  "ops.profile.lead_out_length.help",
  "ops.profile.lead_out_radius.help",
  "ops.profile.leads.legend",
  "ops.profile.legend",
  "ops.profile.length.label",
  "ops.profile.offset.label",
  "ops.profile.radius.label",
  "ops.profile.side.inside",
  "ops.profile.side.on",
  "ops.profile.side.outside",
  "ops.raster.power_curve.legend",
  "ops.raster.scan.along_x",
  "ops.raster.scan.along_y",
  "ops.raster.scan.bidirectional",
  "ops.raster.scan.legend",
  "ops.raster.scan.lift_between",
  "ops.raster.source.legend",
  "ops.raster_engrave.decoding",
  "ops.raster_engrave.dimensions.hint",
  "ops.raster_engrave.direction.label",
  "ops.raster_engrave.estimate.label",
  "ops.raster_engrave.estimate_rough",
  "ops.raster_engrave.histogram.hint",
  "ops.raster_engrave.histogram_level.hint",
  "ops.raster_engrave.image.label",
  "ops.raster_engrave.intro.hint",
  "ops.raster_engrave.level.help",
  "ops.raster_engrave.level.label",
  "ops.raster_engrave.link.help",
  "ops.raster_engrave.link.label",
  "ops.raster_engrave.load_error.hint",
  "ops.raster_engrave.load_image",
  "ops.raster_engrave.matrix.help",
  "ops.raster_engrave.matrix.label",
  "ops.raster_engrave.max_s.help",
  "ops.raster_engrave.max_s.label",
  "ops.raster_engrave.min_s.help",
  "ops.raster_engrave.min_s.label",
  "ops.raster_engrave.overscan.help",
  "ops.raster_engrave.overscan.label",
  "ops.raster_engrave.power_curve.bayer",
  "ops.raster_engrave.power_curve.floyd_steinberg",
  "ops.raster_engrave.power_curve.label",
  "ops.raster_engrave.power_curve.linear",
  "ops.raster_engrave.power_curve.threshold",
  "ops.raster_engrave.power_s.help",
  "ops.raster_engrave.power_s.label",
  "ops.raster_engrave.preview.help",
  "ops.raster_engrave.resolution.help",
  "ops.raster_engrave.resolution.label",
  "ops.raster_engrave.width.help",
  "ops.raster_engrave.width.label",
  "ops.relief.depth.legend",
  "ops.relief.finish.legend",
  "ops.relief.scan.along_x",
  "ops.relief.scan.along_y",
  "ops.relief.source.legend",
  "ops.relief_mill.decoding",
  "ops.relief_mill.depth_limit.help",
  "ops.relief_mill.depth_limit.hint",
  "ops.relief_mill.depth_limit.label",
  "ops.relief_mill.depth_limit.placeholder",
  "ops.relief_mill.dimensions.hint",
  "ops.relief_mill.image.label",
  "ops.relief_mill.invert.help",
  "ops.relief_mill.invert.label",
  "ops.relief_mill.load_error.hint",
  "ops.relief_mill.load_image",
  "ops.relief_mill.load_stl",
  "ops.relief_mill.scallop.help",
  "ops.relief_mill.scallop.label",
  "ops.relief_mill.scan.label",
  "ops.relief_mill.step.help",
  "ops.relief_mill.step.label",
  "ops.relief_mill.stepover.help",
  "ops.relief_mill.stepover.label",
  "ops.relief_mill.stepover.placeholder",
  "ops.relief_mill.stl.dimensions.hint",
  "ops.relief_mill.stl.no_footprint",
  "ops.relief_mill.surfacing.hint",
  "ops.relief_mill.width.help",
  "ops.relief_mill.width.label",
  "ops.relief_mill.width.stl_locked",
  "ops.relief_mill.z_max.help",
  "ops.relief_mill.z_max.label",
  "ops.relief_mill.z_min.help",
  "ops.relief_mill.z_min.label",
  "ops.tabs.clear",
  "ops.tabs.count.help",
  "ops.tabs.count.label",
  "ops.tabs.disconnected.help",
  "ops.tabs.disconnected.hint",
  "ops.tabs.height.help",
  "ops.tabs.height.label",
  "ops.tabs.legend",
  "ops.tabs.manual.help",
  "ops.tabs.manual.hint",
  "ops.tabs.manual.placed",
  "ops.tabs.mode.help",
  "ops.tabs.mode.label",
  "ops.tabs.ramp.summary",
  "ops.tabs.ramp_angle.help",
  "ops.tabs.ramp_angle.label",
  "ops.tabs.type.label",
  "ops.tabs.type.ramp",
  "ops.tabs.type.ramp.help",
  "ops.tabs.type.rectangle",
  "ops.tabs.type.rectangle.help",
  "ops.tabs.width.help",
  "ops.tabs.width.label",
  "ops.thread.climb.help",
  "ops.thread.climb.label",
  "ops.thread.direction.help",
  "ops.thread.direction.label",
  "ops.thread.legend",
  "ops.thread.pitch.help",
  "ops.thread.pitch.label",
  "ops.thread.side.external",
  "ops.thread.side.internal",
  "ops.thread.source.help",
  "ops.thread.source.hint",
  "ops.vcarve.advanced.summary",
  "ops.vcarve.duplicate_as_inlay_plug",
  "ops.vcarve.inlay_plug.help",
  "ops.vcarve.inlay_plug.label",
  "ops.vcarve.legend",
  "ops.vcarve.max_width.help",
  "ops.vcarve.max_width.label",
  "ops.vcarve.max_width.placeholder",
  "ops.vcarve.mode.help",
  "ops.vcarve.mode.label",
  "ops.vcarve.mode.medial_axis",
  "ops.vcarve.mode.perimeter",
  "ops.vcarve.refine_pass.help",
  "ops.vcarve.refine_pass.label",
  "ops.vcarve.refine_pass.not_implemented",
  "ops.vcarve.source_inset.help",
  "ops.vcarve.source_inset.label",
  "ops.waterline.floor.help",
  "ops.waterline.floor.label",
  "ops.waterline.floor.placeholder",
  "ops.waterline.levels.legend",
  "ops.waterline.load_stl",
  "ops.waterline.needs_stl.hint",
  "ops.waterline.roughing.hint",
  "ops.waterline.stepover.help",
  "ops.waterline.stepover.label",
  "ops.waterline.z_step.help",
  "ops.waterline.z_step.label",
  "panel.drag_to_move",
  "panel.drag_to_resize",
  "panel.header.aria",
  "panel.header.aria_draggable",
  "phonewarn.chip.generate",
  "phonewarn.chip.ok",
  "phonewarn.chip.stale",
  "phonewarn.copied",
  "phonewarn.copy",
  "phonewarn.empty",
  "phonewarn.fix_wcs",
  "phonewarn.panel.aria",
  "phonewarn.panel.title",
  "phonewarn.title.generating",
  "phonewarn.title.many",
  "phonewarn.title.no_program",
  "phonewarn.title.no_warnings",
  "phonewarn.title.one",
  "phonewarn.title.stale",
  "playback.next_op",
  "playback.next_op.named",
  "playback.pause",
  "playback.play",
  "playback.position",
  "playback.prev_op",
  "playback.prev_op.named",
  "playback.scrub.exact",
  "playback.scrub.forward",
  "playback.speed",
  "playback.speed.aria",
  "playback.tick.jump",
  "playback.tick.silenced",
  "playback.valuetext",
  "playback.valuetext.named",
  "post.axes.axis",
  "post.axes.disabled",
  "post.axes.enable_aria",
  "post.axes.feed",
  "post.axes.format",
  "post.axes.format_aria",
  "post.axes.i_arc",
  "post.axes.j_arc",
  "post.axes.name",
  "post.axes.name_aria",
  "post.axes.on",
  "post.axes.scale",
  "post.axes.scale.title",
  "post.axes.scale_aria",
  "post.axes.spindle",
  "post.coolant_flood_off",
  "post.coolant_flood_on",
  "post.coolant_mist_on",
  "post.discard_prompt",
  "post.export_json",
  "post.extension",
  "post.file_output",
  "post.import_err.axes_incomplete",
  "post.import_err.parse",
  "post.import_json",
  "post.keep_editing",
  "post.line_ending",
  "post.line_ending.crlf",
  "post.line_ending.lf",
  "post.per_axis",
  "post.per_axis.hint_after",
  "post.per_axis.hint_before",
  "post.per_axis.hint_mid",
  "post.per_axis.override",
  "post.preview",
  "post.preview.sub",
  "post.profile_name",
  "post.profile_name.placeholder",
  "post.program_end",
  "post.program_start",
  "post.save",
  "post.templates",
  "post.templates.case_insensitive",
  "post.templates.marker.diameter",
  "post.templates.marker.feed",
  "post.templates.marker.newline",
  "post.templates.marker.spindle",
  "post.templates.marker.tool_name",
  "post.templates.marker.tool_num",
  "post.templates.markers",
  "post.title",
  "post.tokens.d",
  "post.tokens.f",
  "post.tokens.intro_after",
  "post.tokens.intro_before",
  "post.tokens.n",
  "post.tokens.nl",
  "post.tokens.op",
  "post.tokens.project",
  "post.tokens.s",
  "post.tokens.summary",
  "post.tokens.t",
  "post.tokens.tools",
  "post.tokens.version",
  "post.tool_change",
  "recent.button",
  "recent.clear",
  "recent.open_hint",
  "report.brand_subtitle",
  "report.generated_by",
  "report.ops.col.depth",
  "report.ops.col.kind",
  "report.ops.col.name",
  "report.ops.col.source",
  "report.ops.col.status",
  "report.ops.col.tool",
  "report.ops.empty",
  "report.ops.title",
  "report.print",
  "report.save_markdown",
  "report.source.all_geometry",
  "report.source.no_layers",
  "report.source.objects",
  "report.stats.empty",
  "report.stats.enabled_ops",
  "report.stats.objects",
  "report.stats.offsets",
  "report.stats.segments",
  "report.stats.title",
  "report.status.error",
  "report.status.not_generated",
  "report.status.ok",
  "report.status.pause",
  "report.status.warnings",
  "report.time.arc",
  "report.time.cut",
  "report.time.plunge",
  "report.time.rapid",
  "report.time.retract",
  "report.time.spindle_warmup",
  "report.time.title",
  "report.time.tool_change",
  "report.time.total",
  "report.title",
  "report.tools.col.diameter",
  "report.tools.col.feed",
  "report.tools.col.kind",
  "report.tools.col.name",
  "report.tools.col.speed",
  "report.tools.empty",
  "report.tools.title",
  "report.untitled_project",
  "report.warnings.summary",
  "report.warnings.title",
  "scene3d.ctx.dismiss",
  "scene3d.ctx.hint",
  "scene3d.ctx.new_op",
  "scene3d.empty.sub",
  "scene3d.empty.title",
  "settings.appearance.language",
  "settings.appearance.language.auto",
  "settings.appearance.language.help",
  "settings.appearance.theme",
  "settings.appearance.theme.auto",
  "settings.appearance.theme.dark",
  "settings.appearance.theme.light",
  "settings.group.appearance",
  "settings.group.performance",
  "settings.group.preview",
  "settings.group.safety",
  "settings.group.snap",
  "settings.group.sources",
  "settings.group.view",
  "settings.group_nav.aria",
  "settings.performance.caps_hint",
  "settings.performance.exact_rewind",
  "settings.performance.exact_rewind.hint",
  "settings.performance.max_render_triangles",
  "settings.performance.max_sim_cells",
  "settings.performance.solid_default",
  "settings.preview.arrow_density",
  "settings.preview.arrow_off",
  "settings.preview.cell_resolution",
  "settings.preview.cell_resolution.auto",
  "settings.preview.cell_resolution.manual",
  "settings.preview.cell_size",
  "settings.preview.cell_size.title",
  "settings.preview.deviation_overlay",
  "settings.preview.deviation_overlay_help",
  "settings.preview.deviation_tolerance",
  "settings.preview.edge_color",
  "settings.preview.edge_opacity",
  "settings.preview.intro",
  "settings.preview.line_width",
  "settings.preview.solid_color",
  "settings.preview.solid_opacity",
  "settings.safety.auto_regenerate",
  "settings.safety.auto_regenerate.title",
  "settings.safety.auto_run_sim",
  "settings.safety.block_critical",
  "settings.safety.block_work_area",
  "settings.safety.block_work_area.title",
  "settings.safety.hint",
  "settings.snap.center",
  "settings.snap.center.help",
  "settings.snap.endpoint",
  "settings.snap.endpoint.help",
  "settings.snap.grid",
  "settings.snap.grid.help",
  "settings.snap.grid_step",
  "settings.snap.grid_step.title",
  "settings.snap.hint",
  "settings.snap.intersection",
  "settings.snap.intersection.help",
  "settings.snap.midpoint",
  "settings.snap.midpoint.help",
  "settings.sources.auto_reload",
  "settings.sources.hint",
  "settings.title",
  "settings.view.preview_style",
  "settings.view.preview_style.both",
  "settings.view.preview_style.solid",
  "settings.view.preview_style.wireframe",
  "settings.view.show_stock_box",
  "shortcuts.canvas2d.add_selection",
  "shortcuts.canvas2d.context",
  "shortcuts.canvas2d.pan",
  "shortcuts.canvas2d.remove_selection",
  "shortcuts.canvas2d.select",
  "shortcuts.global.add_text",
  "shortcuts.global.escape",
  "shortcuts.global.redo",
  "shortcuts.global.show_help",
  "shortcuts.global.undo",
  "shortcuts.section.canvas2d",
  "shortcuts.section.global",
  "shortcuts.section.touch",
  "shortcuts.section.view3d",
  "shortcuts.title",
  "shortcuts.touch.bottom_handles",
  "shortcuts.touch.edge_swipe",
  "shortcuts.touch.fit_view",
  "shortcuts.touch.long_press",
  "shortcuts.touch.multi_select",
  "shortcuts.touch.one_finger",
  "shortcuts.touch.pinch",
  "shortcuts.touch.pull_down",
  "shortcuts.touch.tap",
  "shortcuts.touch.two_finger",
  "shortcuts.view3d.orbit",
  "shortcuts.view3d.pan",
  "shortcuts.zoom",
  "stock.dimensions",
  "stock.flip",
  "stock.flip.axis",
  "stock.flip.axis.x",
  "stock.flip.axis.x.hint",
  "stock.flip.axis.y",
  "stock.flip.axis.y.hint",
  "stock.flip.badge",
  "stock.flip.dowel_count",
  "stock.flip.dowel_dia",
  "stock.flip.dowel_margin",
  "stock.flip.dowel_margin.title",
  "stock.flip.enable",
  "stock.length",
  "stock.margin",
  "stock.margin.title",
  "stock.mode",
  "stock.mode.auto",
  "stock.mode.manual",
  "stock.offset_z.title",
  "stock.origin_offset",
  "stock.snap_bbox",
  "stock.snap_bbox.title",
  "stock.thickness",
  "stock.wcs",
  "stock.width",
  "stock.work_origin",
  "stock.work_origin.title",
  "textlist.activate.aria",
  "textlist.add",
  "textlist.add.aria",
  "textlist.add.title",
  "textlist.align.center",
  "textlist.align.left",
  "textlist.align.right",
  "textlist.collapse.aria",
  "textlist.collapse.title",
  "textlist.delete.aria",
  "textlist.delete.title",
  "textlist.empty",
  "textlist.expand.title",
  "textlist.field.align",
  "textlist.field.font",
  "textlist.field.letter_gap",
  "textlist.field.line_spacing",
  "textlist.field.rotation",
  "textlist.field.size",
  "textlist.field.text",
  "textlist.field.width",
  "textlist.field.width.title",
  "textlist.field.x",
  "textlist.field.y",
  "textlist.snap_origin",
  "textlist.snap_origin.title",
  "textlist.snap_origin.title_disabled",
  "textlist.title",
  "textlist.toggle_form.aria",
  "toast.dismiss",
  "toast.queue.more",
  "toast.queue.title",
  "toast.report_bug",
  "toolform.add_row",
  "toolform.angle",
  "toolform.angle.title",
  "toolform.cut_height",
  "toolform.cut_height.title",
  "toolform.delete_row.title",
  "toolform.dovetail_dia",
  "toolform.dovetail_dia.title",
  "toolform.form_profile",
  "toolform.form_profile.title",
  "toolform.generate_dovetail",
  "toolform.generate_dovetail.title",
  "toolform.generate_tslot",
  "toolform.generate_tslot.title",
  "toolform.head_thick",
  "toolform.head_thick.title",
  "toolform.min_rows_hint",
  "toolform.neck_dia",
  "toolform.neck_dia.title",
  "toolform.neck_length",
  "toolform.neck_length.title",
  "toolform.radius",
  "toolform.tslot_head_dia",
  "toolform.tslot_head_dia.title",
  "toolform.z_above_tip",
  "tools.add",
  "tools.apply.invalid.title",
  "tools.bullnose",
  "tools.bullnose.corner_radius",
  "tools.bullnose.corner_radius.title",
  "tools.bullnose.title",
  "tools.clear_filters",
  "tools.col.coolant",
  "tools.col.dflt_step",
  "tools.col.dflt_step.title",
  "tools.col.diameter.title",
  "tools.col.feed",
  "tools.col.feed.title",
  "tools.col.flutes",
  "tools.col.flutes.title",
  "tools.col.id.title",
  "tools.col.kind",
  "tools.col.kind.title",
  "tools.col.name",
  "tools.col.name.title",
  "tools.col.plunge",
  "tools.col.plunge.title",
  "tools.col.speed",
  "tools.col.speed.title",
  "tools.col.tip_angle",
  "tools.col.tip_angle.title",
  "tools.col.tip_diameter",
  "tools.comment",
  "tools.comment.placeholder",
  "tools.comment.title",
  "tools.compression",
  "tools.compression.title",
  "tools.compression.transition",
  "tools.compression.transition.placeholder",
  "tools.compression.transition.title",
  "tools.coolant.flood",
  "tools.coolant.mist",
  "tools.coolant.off",
  "tools.count.filtered",
  "tools.count.many",
  "tools.count.one",
  "tools.drag",
  "tools.drag.offset",
  "tools.drag.offset.title",
  "tools.drag.self_align",
  "tools.drag.self_align.title",
  "tools.drag.title",
  "tools.drill.feed",
  "tools.drill.peck",
  "tools.drill.peck.title",
  "tools.drill.plunge",
  "tools.drill.rpm",
  "tools.drill.xy_overlap",
  "tools.drill.xy_overlap.title",
  "tools.field.na",
  "tools.file.load_add",
  "tools.file.load_add.title",
  "tools.file.load_replace",
  "tools.file.load_replace.inventory.title",
  "tools.file.load_replace.project.title",
  "tools.file.save.inventory.title",
  "tools.file.save.project.title",
  "tools.filter.all",
  "tools.filter.clear",
  "tools.filter.kind",
  "tools.filter.runs_on",
  "tools.filter.runs_on.any",
  "tools.filter.runs_on.drag",
  "tools.filter.runs_on.laser",
  "tools.filter.runs_on.mill",
  "tools.filter.runs_on.plasma",
  "tools.filter.runs_on.title",
  "tools.finish.feed",
  "tools.finish.plunge",
  "tools.finish.rpm",
  "tools.hidden.many",
  "tools.hidden.one",
  "tools.hide_incompatible",
  "tools.holder.cone.bottom_diameter",
  "tools.holder.cone.top_diameter",
  "tools.holder.cyl.diameter",
  "tools.holder.flute_length",
  "tools.holder.flute_length.title",
  "tools.holder.kind.cone",
  "tools.holder.kind.cylinder",
  "tools.holder.kind.none",
  "tools.holder.kind.stepped",
  "tools.holder.label",
  "tools.holder.length",
  "tools.holder.overall_length",
  "tools.holder.overall_length.title",
  "tools.holder.preset",
  "tools.holder.preset.apply",
  "tools.holder.preset.title",
  "tools.holder.runs_on",
  "tools.holder.runs_on.title",
  "tools.holder.shank_diameter",
  "tools.holder.shank_diameter.placeholder",
  "tools.holder.shank_diameter.title",
  "tools.holder.stepped.cone_length",
  "tools.holder.stepped.cone_top_diameter",
  "tools.holder.stepped.cyl_diameter",
  "tools.holder.stepped.cyl_length",
  "tools.holder.stickout",
  "tools.holder.stickout.title",
  "tools.laser",
  "tools.laser.kerf",
  "tools.laser.kerf.title",
  "tools.laser.lead_in",
  "tools.laser.lead_in.title",
  "tools.laser.pierce_time",
  "tools.laser.pierce_time.title",
  "tools.laser.title",
  "tools.no_match",
  "tools.pager.next",
  "tools.pager.prev",
  "tools.pager.status",
  "tools.pass_overrides",
  "tools.pass_overrides.title",
  "tools.plasma",
  "tools.plasma.cut_height",
  "tools.plasma.cut_height.title",
  "tools.plasma.kerf",
  "tools.plasma.kerf.title",
  "tools.plasma.pierce_delay",
  "tools.plasma.pierce_delay.title",
  "tools.plasma.pierce_height",
  "tools.plasma.pierce_height.title",
  "tools.plasma.title",
  "tools.row.delete.aria",
  "tools.row.delete.disabled",
  "tools.row.delete.title",
  "tools.row.dflt_step.invalid.title",
  "tools.row.dflt_step.title",
  "tools.row.diameter.invalid.title",
  "tools.row.expand.collapse.aria",
  "tools.row.expand.collapse.title",
  "tools.row.expand.expand.aria",
  "tools.row.expand.expand.title",
  "tools.row.feed.drill.title",
  "tools.row.feed.invalid.title",
  "tools.row.name.title",
  "tools.row.plunge.invalid.title",
  "tools.row.speed.invalid.title",
  "tools.row.tip_angle.title",
  "tools.row.tip_diameter.invalid.title",
  "tools.save.invalid.title",
  "tools.search.placeholder",
  "tools.search.title",
  "tools.show_all",
  "tools.show_all.title",
  "tools.showing_all",
  "tools.spindle_dir",
  "tools.spindle_dir.ccw",
  "tools.spindle_dir.cw",
  "tools.spindle_dir.disabled.drag_knife",
  "tools.spindle_dir.disabled.laser",
  "tools.spindle_dir.disabled.plasma",
  "tools.spindle_dir.title",
  "tools.spindle_warmup",
  "tools.spindle_warmup.title",
  "tools.thread",
  "tools.thread.pitch",
  "tools.thread.pitch.title",
  "tools.thread.title",
  "tools.title",
  "tools.validation_msg",
  "tools.wear",
  "tools.wear.calibrate",
  "tools.wear.calibrate.title",
  "tools.wear.cuts_as",
  "tools.wear.last_calibrated",
  "tools.wear.never",
  "tools.wear.offset",
  "tools.wear.offset.title",
  "tools.wear.stale",
  "tools.wear.stale.title",
  "tools.wear.title",
  "tools.whirl",
  "tools.whirl.enable",
  "tools.whirl.extra_width",
  "tools.whirl.extra_width.title",
  "tools.whirl.stride",
  "tools.whirl.stride.title",
  "tools.whirl.title",
  "tools.whirl.z_wobble",
  "tools.whirl.z_wobble.title",
  "tools.z_shift",
  "tools.z_shift.title",
  "warn.chamfer_non_vbit",
  "warn.chamfer_width_clamped_to_reach",
  "warn.compression_transition_above_cut",
  "warn.cps_unsupported_op",
  "warn.dovetail_requires_rough_channel.generic",
  "warn.dovetail_requires_rough_channel.known",
  "warn.drill_spot_depth_non_negative",
  "warn.drill_spot_tool_missing",
  "warn.dual_tool_no_toolchange",
  "warn.feed_clamped_above_max",
  "warn.fixed_sensor_reference_not_first",
  "warn.frame_padding_below_tool_radius",
  "warn.gcode_include_empty",
  "warn.gcode_include_lines_skipped",
  "warn.gcode_include_unknown_variable",
  "warn.gcode_include_unsim_line",
  "warn.grbl_atc_no_toolchange_template",
  "warn.grbl_fixed_sensor_no_offset",
  "warn.halfpipe_depth_limited",
  "warn.halfpipe_radius_mismatch",
  "warn.halfpipe_tool_reach_exceeded",
  "warn.helix_radius_unfittable",
  "warn.multi_tool_manual_machine",
  "warn.nocontour_ignores_finish_allowance",
  "warn.op_machine_mode_mismatch",
  "warn.op_order_suspect.drill_after_profile",
  "warn.op_order_suspect.finish_before_rough",
  "warn.op_source_empty.layer",
  "warn.op_source_empty.object",
  "warn.op_source_missing_layer",
  "warn.op_source_missing_object",
  "warn.out_of_stock",
  "warn.out_of_stock.at_line",
  "warn.out_of_work_area",
  "warn.out_of_work_area.at_line",
  "warn.parallel_offset_panicked",
  "warn.pierce_on_contour_no_lead.laser",
  "warn.pierce_on_contour_no_lead.plasma",
  "warn.plunge_overridden",
  "warn.pocket_cascade_truncated",
  "warn.pocket_fill_incomplete",
  "warn.ramp_arcs_at_boundary",
  "warn.raster_too_large",
  "warn.relief_missing_roughing",
  "warn.relief_source_invalid",
  "warn.relief_tool_reach_exceeded",
  "warn.rotate_offsets_far_from_approach",
  "warn.spindle_speed_clamped_above_max",
  "warn.spindle_speed_clamped_below_min",
  "warn.step_unspecified",
  "warn.stock_origin_outside_geometry_bbox",
  "warn.stufenfase_no_toolchange",
  "warn.stufenfase_non_circle_skipped",
  "warn.tabs_count_clamped_short_contour",
  "warn.tabs_with_trochoidal_unsupported",
  "warn.thread_dz_less_than_pitch",
  "warn.thread_no_circles",
  "warn.thread_no_depth",
  "warn.thread_tool_too_large",
  "warn.thread_whirl_radius_clamped",
  "warn.thread_zero_bore",
  "warn.tool_geometry_impossible",
  "warn.tool_incompatible_with_machine_mode",
  "warn.tool_kind_mismatch.dovetail_non_form",
  "warn.tool_kind_mismatch.halfpipe_circular_arc",
  "warn.tool_kind_mismatch.halfpipe_vbottom",
  "warn.tool_kind_mismatch.pocket_dragknife",
  "warn.tool_kind_mismatch.pocket_drill",
  "warn.tool_kind_mismatch.profile_drill",
  "warn.tool_kind_mismatch.relief_non_round",
  "warn.tool_kind_mismatch.thread_dragknife",
  "warn.tool_kind_mismatch.thread_drill",
  "warn.tool_kind_mismatch.thread_laser",
  "warn.tool_kind_mismatch.tslot_non_form",
  "warn.tool_kind_mismatch.vcarve_non_vbit",
  "warn.tool_tip_angle_clamped",
  "warn.tool_too_large",
  "warn.trochoidal_incomplete",
  "warn.tslot_requires_stem_slot.generic",
  "warn.tslot_requires_stem_slot.known",
  "warn.two_sided_overlap",
  "warn.vcarve_below_tip_radius.full_none",
  "warn.vcarve_below_tip_radius.full_some",
  "warn.vcarve_below_tip_radius.perimeter",
  "warn.vcarve_depth_limited",
  "warn.vcarve_no_closed_region",
  "warn.vcarve_no_medial_axis",
  "warn.zero_rate_emitted",
  "warn.zigzag_stride_clamped_below_minimum",
];
