#!/usr/bin/env bash
#
# Repair the post-repo-move Tauri build break (ivac-nild).
#
# WHY: this repo was physically moved (/home/soenke/wiaconstructor ->
# /home/soenke/ivacam), which baked the OLD absolute path into the
# build-script OUTPUT of the Tauri crate chain — `output`, `root-output`
# and `*.d` depinfo under target/**/build/<crate>-<hash>/. Tauri's
# permission-ACL codegen reads a `DEP_TAURI_*` OUT_DIR back out of those
# files, so `cargo tauri build` / `android build` then dies with e.g.:
#
#   failed to read plugin permissions:
#   .../wiaconstructor/target/.../build/tauri-<hash>/out/permissions/
#   app/autogenerated/commands/app_hide.toml: No such file or directory
#
# THE SURGICAL FIX is to drop ONLY the fingerprints + build-script output
# of the crates whose codegen bakes that path — the `tauri` crate, the
# first-party tauri plugins, and our app crate `ivac-tauri` — so cargo
# re-runs just those build scripts and regenerates the ACL at the live
# path. We deliberately do NOT touch:
#   * tauri-runtime / tauri-runtime-wry  -> recompiling wry + webkit2gtk
#     is the slow thing we are avoiding; their stale depinfo is benign
#     (a missing .d entry only makes cargo rebuild, never a hard error).
#   * libc / serde / pango-sys / ...     -> benign non-Tauri stale refs.
#
# The dir pattern below matches `tauri-<16hex>` but NOT
# `tauri-runtime[-wry]-<hash>` / `tauri-build|codegen|macros|utils-<hash>`
# (those have a non-hash first segment), so wry is provably untouched.
#
# Idempotent + no-op safe: the guard greps the exact same set of dirs the
# clean removes, so a second run reports "nothing stale, skipping". The
# grep marker is the dead path segment `wiaconstructor` — scoped to the
# Tauri-family dirs so the ~6800 benign libc/serde refs never trip it.
#
# Usage:
#   scripts/fix-stale-target-paths.sh          # detect, then repair if stale
#   scripts/fix-stale-target-paths.sh --check   # detect only; exit 1 if stale
#
# See docs/BUILDING.md (Versioning / stale-target note) and the
# `build-stale-path-after-repo-move` project memory.
set -euo pipefail
cd "$(dirname "$0")/.."

TAG=fix-stale-target-paths
MARKER=wiaconstructor # the dead pre-move path segment to grep for

check_only=0
case "${1:-}" in
  --check | -n)
    check_only=1
    ;;
  '') ;;
  *)
    echo "$TAG: unknown argument '$1' (use --check or no args)" >&2
    exit 2
    ;;
esac

# Precise dir basename regex: <family>-<16 hex cargo hash>. Matches the
# `tauri` crate, `tauri-plugin-<name>`, and `ivac-tauri`; excludes
# tauri-runtime[-wry], tauri-build/codegen/macros/utils (non-hash segment).
FAMILY_RE='.*/(tauri|tauri-plugin-[a-z-]+|ivac-tauri)-[0-9a-f]{16}'

ANDROID_TRIPLES=(
  aarch64-linux-android
  armv7-linux-androideabi
  i686-linux-android
  x86_64-linux-android
)

# Sweep host debug + release + each android triple's debug that exists.
roots=()
for r in debug release; do
  [[ -d target/$r ]] && roots+=("$r")
done
for t in "${ANDROID_TRIPLES[@]}"; do
  [[ -d target/$t/debug ]] && roots+=("$t/debug")
done

# Print every Tauri-family build/.fingerprint dir under the swept roots,
# one per line (NUL would be safer, but cargo target paths never contain
# spaces).
family_dirs() {
  local r sub
  for r in "${roots[@]}"; do
    for sub in build .fingerprint; do
      [[ -d target/$r/$sub ]] || continue
      find "target/$r/$sub" -mindepth 1 -maxdepth 1 -type d \
        -regextype posix-extended -regex "$FAMILY_RE" 2>/dev/null
    done
  done
}

# Files under those dirs still carrying the dead path marker.
stale_files() {
  local dirs
  dirs=$(family_dirs)
  [[ -n "$dirs" ]] || return 0
  printf '%s\n' "$dirs" | xargs -r grep -rlI "$MARKER" 2>/dev/null || true
}

mapfile -t stale < <(stale_files)
n=${#stale[@]}

if [[ $n -eq 0 ]]; then
  echo "$TAG: nothing stale, skipping (no '$MARKER' refs in Tauri-family target dirs)"
  exit 0
fi

echo "$TAG: found $n stale Tauri-family file(s) referencing the dead '$MARKER' path"

if [[ $check_only -eq 1 ]]; then
  # Report the offending dirs (deduped) so a caller can see the blast radius.
  printf '%s\n' "${stale[@]}" | sed -E 's#(/(build|\.fingerprint)/[^/]+)/.*#\1#' | sort -u |
    while IFS= read -r d; do echo "  stale: $d"; done
  echo "$TAG: run 'scripts/fix-stale-target-paths.sh' (no --check) to repair" >&2
  exit 1
fi

# Repair: remove the fingerprint + build-script output of the affected
# crates so cargo rebuilds just them. rm -rf of a non-matching glob is a
# no-op, so this is safe to re-run.
removed=0
while IFS= read -r dir; do
  [[ -n "$dir" ]] || continue
  rm -rf -- "$dir"
  removed=$((removed + 1))
done < <(family_dirs)
echo "$TAG: removed $removed Tauri-family fingerprint/build dir(s) across: ${roots[*]}"

# Verify the repair actually cleared the marker (guards against a family
# we failed to match).
mapfile -t leftover < <(stale_files)
if [[ ${#leftover[@]} -ne 0 ]]; then
  echo "$TAG: WARNING — ${#leftover[@]} stale ref(s) remain after clean:" >&2
  printf '  %s\n' "${leftover[@]}" >&2
  exit 1
fi

echo "$TAG: done — the next 'cargo tauri build' / 'android build' will rebuild"
echo "$TAG: tauri + plugins + ivac-tauri; the webkit2gtk / wry native bindings"
echo "$TAG: are left compiled, so the slow C-FFI stack is not rebuilt"
