<script lang="ts">
  /// Printable project-summary report. Single-column layout that prints
  /// cleanly via window.print() — operators can hand-off the printout
  /// with the cut. Pulls every value from data the frontend already has
  /// (project state + project.gen.generated). No new backend computation;
  /// deeper analyses (material removed, per-op time breakdown) deferred
  /// to a follow-up — the bd issue notes 4-5 days of work, this MVP ships
  /// the user-visible 80%.
  import Modal from './Modal.svelte';
  import { project, type OpEntry } from '../state/project.svelte';
  import { isProgramOnlyOp } from '../state/op_types';
  import type { TimeEstimate } from '../api/types';
  import { buildReportMarkdown, type ReportData } from './report-markdown';
  import { saveReportMarkdown } from '../services/file_ops';
  import { isAndroid } from '../api/env';
  import { t } from '../i18n';
  import { warningMessage } from './warning-display';

  /// Full build identity for the "Generated by" line + Markdown front
  /// matter. Package semver + git-describe + build date, from the vite
  /// defines (see vite.config.ts).
  const pkgVersion = typeof __IVAC_PKG_VERSION__ === 'string' ? __IVAC_PKG_VERSION__ : '0.0.0';
  const buildVersion =
    typeof __IVAC_BUILD_VERSION__ === 'string' ? __IVAC_BUILD_VERSION__ : 'unknown';
  const buildDate = typeof __IVAC_BUILD_DATE__ === 'string' ? __IVAC_BUILD_DATE__ : '';
  const generatedBy =
    `ivaCAM v${pkgVersion}` +
    (buildVersion && buildVersion !== 'unknown' ? ` (${buildVersion})` : '') +
    (buildDate ? `, built ${buildDate}` : '');

  // Local HH:MM:SS formatter — mirrors the one in GenerateBar but kept
  // self-contained so the report stays printable in isolation.
  function formatHms(s: number | undefined): string {
    if (!s || !isFinite(s) || s < 0) return '00:00:00';
    const total = Math.round(s);
    const h = Math.floor(total / 3600);
    const m = Math.floor((total % 3600) / 60);
    const sec = total % 60;
    return [h, m, sec].map((n) => String(n).padStart(2, '0')).join(':');
  }

  interface Props {
    open: boolean;
    onClose: () => void;
  }
  let { open, onClose }: Props = $props();

  const now = new Date();
  const date = $derived(now.toLocaleString());

  const gen = $derived(project.gen.generated);
  const timeEst = $derived<TimeEstimate | null>(
    (gen as { time_estimate?: TimeEstimate } | null)?.time_estimate ?? null,
  );

  const enabledOps = $derived(project.data.operations.filter((o) => o.enabled));
  /// Distinct tool IDs referenced by enabled ops, excluding Pause
  /// (which carries toolId 0 but uses no tool).
  const usedToolIds = $derived(
    Array.from(new Set(enabledOps.filter((o) => o.kind !== 'pause').map((o) => o.toolId))),
  );
  const usedTools = $derived(
    usedToolIds
      .map((id) => project.data.tools.find((t) => t.id === id))
      .filter((t): t is NonNullable<typeof t> => t != null),
  );

  function opSourceSummary(op: OpEntry): string {
    if (op.kind === 'pause') return '—';
    if (op.sourceObjects && op.sourceObjects.length > 0) {
      return t('report.source.objects', { n: op.sourceObjects.length });
    }
    if (op.sourceLayers === null) return t('report.source.all_geometry');
    if (op.sourceLayers.length === 0) return t('report.source.no_layers');
    return op.sourceLayers.map((l) => `"${l}"`).join(', ');
  }

  function opDepth(op: OpEntry): string {
    if (op.kind === 'pause') return '—';
    if ('depth' in op && op.depth != null) {
      return `${op.depth.toFixed(2)} mm`;
    }
    return '—';
  }

  function opStatusLabel(op: OpEntry): string {
    if (op.kind === 'pause') return t('report.status.pause');
    if (!gen) return t('report.status.not_generated');
    const w = (gen.warnings ?? []).filter((x) => x.op_id === op.id);
    if (w.some((x) => x.kind === 'tool_kind_mismatch' || x.kind === 'tool_geometry_impossible')) {
      return t('report.status.error');
    }
    if (w.length > 0) return t('report.status.warnings', { n: w.length });
    return t('report.status.ok');
  }

  const warningsBySeverity = $derived.by(() => {
    const all = gen?.warnings ?? [];
    const bad = all.filter(
      (w) => w.kind === 'tool_kind_mismatch' || w.kind === 'tool_geometry_impossible',
    );
    return { bad: bad.length, warn: all.length - bad.length, top: all.slice(0, 5) };
  });

  function printNow() {
    window.print();
  }

  /// Assemble the report into the pure ReportData shape, then serialize
  /// to Markdown + front matter and save.
  function reportData(): ReportData {
    const toolNameFor = (id: number) =>
      project.data.tools.find((t) => t.id === id)?.name ?? `#${id}`;
    return {
      projectName: projectName(),
      generatedBy,
      dateIso: now.toISOString(),
      dateDisplay: date,
      stats: gen
        ? {
            objects: gen.stats.object_count,
            offsets: gen.stats.offset_count,
            segments: gen.toolpath.length,
            enabledOps: enabledOps.length,
          }
        : null,
      estimatedTime: timeEst ? formatHms(timeEst.total_s) : null,
      tools: usedTools.map((t) => ({ name: t.name, kind: t.kind, diameterMm: t.diameter })),
      ops: enabledOps.map((op) => ({
        name: op.name,
        kind: op.kind,
        // Every program-only kind (Pause, Homing, Probe, CycleMarker,
        // GcodeInclude) is tool-less by design.
        tool: isProgramOnlyOp(op.kind) ? '—' : toolNameFor(op.toolId),
        source: opSourceSummary(op),
        depth: opDepth(op),
        status: opStatusLabel(op),
      })),
      warnings: warningsBySeverity,
    };
  }

  async function saveMarkdown() {
    const base = projectName().replace(/\.[^.]+$/, '') || 'report';
    await saveReportMarkdown(buildReportMarkdown(reportData()), base);
  }

  function projectName(): string {
    const src = project.transformedImport;
    if (src?.filename) return src.filename;
    if (project.activeProjectPath) {
      return project.activeProjectPath.split(/[\\/]/).pop() ?? t('report.untitled_project');
    }
    return t('report.untitled_project');
  }
</script>

{#if open}
  <Modal
    {onClose}
    modalClass="report-modal"
    persistKey="report"
    width="min(640px, 96vw)"
    draggable
    resizable
    ariaLabelledBy="report-title"
  >
    <header class="report-head">
      <h2 id="report-title">{t('report.title')}</h2>
      <button type="button" class="dlg-close" onclick={onClose} aria-label={t('common.close')}
        >×</button
      >
    </header>
    <article class="report-body" id="report-print-root">
      <header class="rb-meta">
        <h1>{projectName()}</h1>
        <p class="rb-sub">{date} · {t('report.brand_subtitle')}</p>
      </header>

      <section>
        <h3>{t('report.stats.title')}</h3>
        {#if gen}
          <table>
            <tbody>
              <tr><th>{t('report.stats.objects')}</th><td>{gen.stats.object_count}</td></tr>
              <tr><th>{t('report.stats.offsets')}</th><td>{gen.stats.offset_count}</td></tr>
              <tr><th>{t('report.stats.segments')}</th><td>{gen.toolpath.length}</td></tr>
              <tr><th>{t('report.stats.enabled_ops')}</th><td>{enabledOps.length}</td></tr>
            </tbody>
          </table>
        {:else}
          <p class="rb-empty">{t('report.stats.empty')}</p>
        {/if}
      </section>

      {#if timeEst}
        <section>
          <h3>{t('report.time.title')}</h3>
          <table>
            <tbody>
              <tr><th>{t('report.time.total')}</th><td>{formatHms(timeEst.total_s)}</td></tr>
              <tr><th>{t('report.time.cut')}</th><td>{formatHms(timeEst.cut_s)}</td></tr>
              <tr><th>{t('report.time.rapid')}</th><td>{formatHms(timeEst.rapid_s)}</td></tr>
              <tr><th>{t('report.time.plunge')}</th><td>{formatHms(timeEst.plunge_s)}</td></tr>
              <tr><th>{t('report.time.retract')}</th><td>{formatHms(timeEst.retract_s)}</td></tr>
              <tr><th>{t('report.time.arc')}</th><td>{formatHms(timeEst.arc_s)}</td></tr>
              <tr
                ><th>{t('report.time.tool_change')}</th><td>{formatHms(timeEst.toolchange_s)}</td
                ></tr
              >
              <tr
                ><th>{t('report.time.spindle_warmup')}</th><td
                  >{formatHms(timeEst.spindle_warmup_s)}</td
                ></tr
              >
            </tbody>
          </table>
        </section>
      {/if}

      <section>
        <h3>{t('report.tools.title')}</h3>
        {#if usedTools.length === 0}
          <p class="rb-empty">{t('report.tools.empty')}</p>
        {:else}
          <table>
            <thead>
              <tr
                ><th>#</th><th>{t('report.tools.col.name')}</th><th
                  >{t('report.tools.col.diameter')}</th
                ><th>{t('report.tools.col.kind')}</th><th>{t('report.tools.col.feed')}</th><th
                  >{t('report.tools.col.speed')}</th
                ></tr
              >
            </thead>
            <tbody>
              {#each usedTools as t (t.id)}
                <tr>
                  <td>{t.id}</td>
                  <td>{t.name}</td>
                  <td>{t.diameter.toFixed(2)}</td>
                  <td>{t.kind}</td>
                  <td>{t.feedRate ?? '—'}</td>
                  <td>{t.speed ?? '—'}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        {/if}
      </section>

      <section>
        <h3>{t('report.ops.title')}</h3>
        {#if enabledOps.length === 0}
          <p class="rb-empty">{t('report.ops.empty')}</p>
        {:else}
          <table>
            <thead>
              <tr>
                <th>#</th><th>{t('report.ops.col.name')}</th><th>{t('report.ops.col.kind')}</th><th
                  >{t('report.ops.col.tool')}</th
                >
                <th>{t('report.ops.col.source')}</th><th>{t('report.ops.col.depth')}</th><th
                  >{t('report.ops.col.status')}</th
                >
              </tr>
            </thead>
            <tbody>
              {#each enabledOps as op (op.id)}
                <tr>
                  <td>{op.id}</td>
                  <td>{op.name}</td>
                  <td>{op.kind}</td>
                  <td>
                    <!-- Program-only ops show a dash, not the
                         missing-tool sentinel. -->
                    {isProgramOnlyOp(op.kind)
                      ? '—'
                      : (project.data.tools.find((t) => t.id === op.toolId)?.name ??
                        `#${op.toolId}`)}
                  </td>
                  <td>{opSourceSummary(op)}</td>
                  <td>{opDepth(op)}</td>
                  <td>{opStatusLabel(op)}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        {/if}
      </section>

      {#if gen && warningsBySeverity.bad + warningsBySeverity.warn > 0}
        <section>
          <h3>{t('report.warnings.title')}</h3>
          <p>
            {t('report.warnings.summary', {
              critical: warningsBySeverity.bad,
              nonCritical: warningsBySeverity.warn,
            })}
          </p>
          {#if warningsBySeverity.top.length > 0}
            <ul class="rb-warn-list">
              {#each warningsBySeverity.top as w, i (i)}
                <li><strong>{w.kind}</strong> — {warningMessage(w, t)}</li>
              {/each}
            </ul>
          {/if}
        </section>
      {/if}

      <footer class="rb-foot">
        <p>{t('report.generated_by', { by: generatedBy, date })}</p>
      </footer>
    </article>
    <!-- Dialog-level action footer — direct Modal child so the floating
         sticky-footer rule pins it to the bottom. Print + Save styled
         like ok/cancel on the other modals. -->
    <footer class="report-foot">
      <button type="button" class="btn-secondary" onclick={saveMarkdown}
        >{t('report.save_markdown')}</button
      >
      <!-- Print relies on window.print(), which the Android System WebView
           doesn't implement (no system print dialog). Hide it there; Save
           Markdown is the export path on Android. -->
      {#if !isAndroid()}
        <button type="button" class="btn-primary" onclick={printNow}>{t('report.print')}</button>
      {/if}
    </footer>
  </Modal>
{/if}

<style>
  .report-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0.5rem 0.6rem 0.4rem;
    border-bottom: 1px solid var(--border);
  }
  .report-head h2 {
    margin: 0;
    font-size: 0.95rem;
  }
  /* Print / Save use global `.btn-primary` / `.btn-secondary`; close ×
     uses `.dlg-close` (audit hbi7) — no local button overrides. */
  /* Dialog action footer, same shape as the other modals'
     <footer> (right-aligned, top border, elevated bg). */
  .report-foot {
    display: flex;
    justify-content: flex-end;
    gap: 0.4rem;
    padding: 0.5rem 0.7rem;
    border-top: 1px solid var(--border);
    background: var(--bg-elevated);
  }
  .report-body {
    padding: 1rem 1.1rem;
    /* In the floating/resizable modal the body is the flex-growing
       scroll region; the dialog box caps total height. A large fixed
       max-height here would fight the resize, so keep it modest. */
    max-height: 75vh;
    overflow-y: auto;
    font-size: 0.85rem;
  }
  .rb-meta h1 {
    margin: 0 0 0.15rem;
    font-size: 1.15rem;
  }
  .rb-sub {
    margin: 0 0 0.8rem;
    font-size: 0.75rem;
    color: var(--text-muted);
  }
  .report-body section {
    margin-bottom: 1.1rem;
  }
  .report-body h3 {
    margin: 0 0 0.35rem;
    font-size: 0.85rem;
    color: var(--text-strong);
    border-bottom: 1px solid var(--border);
    padding-bottom: 0.15rem;
  }
  .report-body table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.78rem;
  }
  .report-body table th,
  .report-body table td {
    text-align: left;
    padding: 0.18rem 0.3rem;
    border-bottom: 1px solid color-mix(in srgb, var(--border) 60%, transparent);
  }
  .report-body table th {
    color: var(--text-muted);
    font-weight: 500;
  }
  .rb-empty {
    color: var(--text-muted);
    font-style: italic;
    font-size: 0.78rem;
  }
  .rb-warn-list {
    margin: 0.3rem 0 0;
    padding-left: 1.1rem;
    font-size: 0.74rem;
  }
  .rb-warn-list li {
    margin-bottom: 0.2rem;
  }
  .rb-warn-list strong {
    color: var(--text-strong);
    font-weight: 600;
    text-transform: uppercase;
    font-size: 0.7rem;
    letter-spacing: 0.04em;
  }
  .rb-foot {
    margin-top: 1.2rem;
    padding-top: 0.4rem;
    border-top: 1px solid var(--border);
    color: var(--text-muted);
    font-size: 0.7rem;
    text-align: right;
  }
  /* Print: hide every overlay chrome and let the report body fill the
     page. Uses :global so it punches through the Modal / app wrappers
     when window.print() fires. */
  @media print {
    :global(body) {
      background: white;
      color: black;
    }
    /* Hide everything outside the report — menubar, toolbar, sidebar,
       canvas, gcode panel, footer, the modal's own overlay backdrop.
       The earlier rule only hid children of `.report-modal`, leaving
       the rest of the app to print on top of the report. */
    :global(body > *) {
      display: none !important;
    }
    /* Re-show only the Modal overlay's tree, then hide its insides
       (we re-enable the report-print-root subtree below). The Modal
       overlay sits as a direct body child via the dialog mount. */
    :global(body > :has(.report-modal)) {
      display: block !important;
    }
    :global(.report-modal) {
      box-shadow: none !important;
      border: 0 !important;
      background: white !important;
      max-height: none !important;
      overflow: visible !important;
    }
    :global(.report-modal *) {
      visibility: hidden;
    }
    :global(.report-modal #report-print-root),
    :global(.report-modal #report-print-root *) {
      visibility: visible;
    }
    :global(.report-modal #report-print-root) {
      position: absolute;
      left: 0;
      top: 0;
      width: 100%;
      padding: 1rem 1.5rem;
      color: black;
    }
    .report-body table th,
    .report-body table td {
      border-color: #ccc;
    }
    .report-body h3 {
      border-color: #999;
    }
  }
</style>
